// Tool data with string icon names for dynamic loading
import React from "react";
import { FileText, Split, Minimize2, RotateCw, Stamp, Lock, Unlock, Text, ListOrdered, Eraser, PlusCircle, Signature, Image as LucideImage, Search, FileHeart, Settings, Bookmark, Table, Layers, CheckCircle, Shield, EyeOff, GitCompare, MessageSquare, Calculator, QrCode, Award, Briefcase, Files, Music2, ArchiveRestore, Code2, Key, Globe, Palette, Link, Sliders, Type, PenTool, Crop } from "lucide-react";

export const toolsData = [
  {
    href: "/pdf/merge",
    title: "Merge PDF",
    description: "Combine multiple PDF files into one seamless document.",
    icon: <Files className="w-8 h-8 text-blue-500 preserve-color" />,
    comingSoon: false,
    keywords: ["merge pdf", "combine pdf", "join pdf files", "pdf merger", "unite pdf", "merge pdf free", "combine pdf online"],
    seoTitle: "Merge PDF Free Online - Combine Multiple PDFs in Seconds",
    seoDescription: "Combine PDFs instantly with drag & drop. Reorder pages, merge unlimited files, download in one click. 100% free, no watermarks, no file uploads to servers.",
    features: ["Drag & drop multiple files", "Reorder before merging", "No file size limits", "100% secure processing"],
    relatedTools: ["/pdf/split", "/organize", "/pdf/compress"],
    category: "Organize & Edit"
  },
  {
    href: "/pdf/split",
    title: "Split PDF",
    description: "Extract specific pages or split a PDF into multiple files.",
    icon: <Split className="w-8 h-8 text-green-500" />,
    comingSoon: false,
    keywords: ["split pdf", "extract pdf pages", "separate pdf", "divide pdf", "pdf splitter", "split pdf free", "pdf page extractor"],
    seoTitle: "Split PDF Free Online - Extract Pages in Seconds | No Sign Up",
    seoDescription: "Split any PDF into separate files instantly. Extract specific pages, divide by ranges, or separate all pages. 100% free, no registration, works offline in your browser.",
    features: ["Extract specific pages", "Split by page ranges", "Preview before splitting", "Download as ZIP"],
    relatedTools: ["/pdf/merge", "/delete-pages", "/organize"],
    category: "Organize & Edit"
  },
  {
    href: "/pdf/compress",
    title: "Compress PDF",
    description: "Reduce PDF file size for easier sharing and storage.",
    icon: <Minimize2 className="w-8 h-8 text-purple-500" />,
    comingSoon: false,
    keywords: ["compress pdf", "reduce pdf size", "optimize pdf", "shrink pdf", "pdf compressor", "compress pdf free", "make pdf smaller"],
    seoTitle: "Compress PDF Free - Reduce File Size Up to 90% | No Limits",
    seoDescription: "Shrink PDF files instantly without losing quality. Reduce size by up to 90% for easy email & sharing. Free, unlimited, no upload - compression happens on your device.",
    features: ["Multiple compression levels", "Quality preservation", "Single-file workflow", "Size preview"],
    relatedTools: ["/pdf/merge", "/pdf/split", "/watermark", "/protect"],
    category: "Security & Privacy"
  },
  {
    href: "/jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert your JPG, PNG, or other images into a PDF document.",
    icon: <LucideImage alt="JPG to PDF Icon" className="w-8 h-8 text-pink-500" />,
    comingSoon: false,
    keywords: ["jpg to pdf", "png to pdf", "image to pdf", "convert images", "photo to pdf"],
    seoTitle: "Convert JPG to PDF Free - Images to PDF in One Click | No Upload",
    seoDescription: "Convert JPG, PNG, and images to PDF instantly. Batch process multiple files, custom page sizes. 100% private - files never leave your browser.",
    features: ["Multiple image formats", "Batch conversion", "Custom page sizes", "Image ordering"],
    relatedTools: ["/pdf-to-jpg", "/pdf/merge", "/pdf/compress"],
    category: "Convert & Create"
  },

  {
    href: "/pdf-to-jpg",
    title: "PDF to JPG",
    description: "Convert PDF pages into high-quality JPG image files.",
    icon: <FileText className="w-8 h-8 text-teal-500" />,
    comingSoon: false,
    keywords: ["pdf to jpg", "pdf to png", "convert pdf to image", "pdf to photo", "extract images"],
    seoTitle: "Convert PDF to JPG Free - High-Quality Images | No Upload",
    seoDescription: "Convert PDF pages to JPG images in your browser with page selection, individual downloads, and ZIP export for multi-page jobs when available.",
    features: ["JPG export", "Page selection", "Multi-page ZIP export", "Browser-only processing"],
    relatedTools: ["/jpg-to-pdf", "/pdf/split", "/pdf/compress", "/ocr"],
    category: "Convert & Create"
  },
  {
    href: "/mp4-to-mp3",
    title: "MP4 to MP3",
    description: "Extract MP3 audio from MP4, WebM, MOV, or MKV videos entirely in your browser.",
    icon: <Music2 className="w-8 h-8 text-emerald-500" />,
    comingSoon: false,
    keywords: ["mp4 to mp3", "video to mp3", "ffmpeg wasm", "extract audio", "convert video audio"],
    seoTitle: "Convert MP4 to MP3 Free - Extract Audio in Seconds | No Upload",
    seoDescription: "Extract MP3 audio from any video instantly. Works with MP4, WebM, MOV, MKV. 100% private - conversion happens on your device.",
    features: ["Runs 100% client-side", "Supports MP4/WebM/MOV/MKV", "High-quality 192 kbps audio", "Reusable FFmpeg cache"],
    relatedTools: ["/html-to-pdf", "/jpg-to-pdf", "/qr-generator"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/zip-extractor",
    title: "ZIP Extractor",
    description: "Unpack ZIP archives locally, preview contents, and download individual files without uploading anything.",
    icon: <ArchiveRestore className="w-8 h-8 text-foreground" />,
    comingSoon: false,
    keywords: ["zip extractor", "unzip files", "zip viewer", "zip to files", "extract zip in browser"],
    seoTitle: "Extract ZIP Files Free - Unzip Online | No Upload Required",
    seoDescription: "Unzip archives instantly in your browser. Preview contents, download individual files. 100% private - files never leave your device.",
    features: ["Runs entirely offline", "Folder-aware preview", "Individual file downloads", "Batch export option"],
    relatedTools: ["/pdf/compress", "/mp4-to-mp3", "/jpg-to-pdf"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/csv-json-converter",
    title: "CSV ↔ JSON",
    description: "Quickly convert comma-separated values to structured JSON (and back) entirely in the browser.",
    icon: <Code2 className="w-8 h-8 text-sky-500" />,
    comingSoon: false,
    keywords: ["csv to json", "json to csv", "csv converter", "json converter", "data transform"],
    seoTitle: "Convert CSV to JSON Free - Instant Data Transformation | No Upload",
    seoDescription: "Transform CSV to JSON (or JSON to CSV) in one click. Edit inline, paste or upload files. 100% browser-based, your data stays private.",
    features: ["Bidirectional conversion", "Inline editing", "File upload and download", "Clipboard shortcuts"],
    relatedTools: ["/zip-extractor", "/mp4-to-mp3", "/html-to-pdf"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/text-case-converter",
    title: "Text Case Converter",
    description: "Flip any snippet between uppercase, lowercase, camelCase, snake_case, and more in seconds.",
    icon: <Text className="w-8 h-8 text-fuchsia-500" />,
    comingSoon: false,
    keywords: ["text case", "uppercase converter", "snake_case", "camelCase", "slug generator"],
    seoTitle: "Text Case Converter Free - UPPERCASE, camelCase & More | Instant",
    seoDescription: "Convert text to uppercase, lowercase, camelCase, snake_case, and more in one click. Unicode-aware, works offline.",
    features: [
      "Uppercase, lowercase, sentence, and title case",
      "camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE",
      "One-click copy or apply back to the editor",
      "Unicode-aware word detection"
    ],
    relatedTools: ["/csv-json-converter", "/markdown-to-html", "/url-encoder"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/url-encoder",
    title: "URL Encoder / Decoder",
    description: "Encode query strings or decode percent-encoded URLs without leaking data to a server.",
    icon: <Code2 className="w-8 h-8 text-amber-500" />,
    comingSoon: false,
    keywords: ["url encoder", "url decoder", "percent encode", "query params"],
    seoTitle: "URL Encoder/Decoder Free - Encode & Decode URLs Instantly",
    seoDescription: "Encode or decode URLs and query parameters in one click. Handles + and %20 automatically. 100% private browser tool.",
    features: [
      "Instant encode/decode with clipboard shortcuts",
      "Handles plus (+) to space normalization",
      "Works offline once loaded",
      "No character length limits"
    ],
    relatedTools: ["/text-case-converter", "/csv-json-converter", "/markdown-to-html"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/base64-encoder",
    title: "Base64 Encoder",
    description: "Convert text or files to Base64 (and back) entirely in your browser.",
    icon: <Code2 className="w-8 h-8 text-lime-500" />,
    comingSoon: false,
    keywords: ["base64", "base64 decoder", "data url", "encode file", "decode base64"],
    seoTitle: "Base64 Encoder/Decoder Free - Convert Text & Files Instantly",
    seoDescription: "Encode or decode Base64 in one click. Text, files, data URLs. Works offline, 100% private - nothing uploaded.",
    features: [
      "Text ↔ Base64 conversion",
      "File drop encoding with size guard",
      "One-click copy actions",
      "Client-side processing only"
    ],
    relatedTools: ["/text-case-converter", "/url-encoder", "/csv-json-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/html-markdown-converter",
    title: "HTML ↔ Markdown Converter",
    description: "Convert documentation, release notes, and CMS snippets between Markdown and HTML with live previews.",
    icon: <Code2 className="w-8 h-8 text-cyan-500" />,
    comingSoon: false,
    keywords: [
      "html to markdown",
      "markdown to html",
      "markup converter",
      "docs tooling",
      "cms prep"
    ],
    seoTitle: "HTML to Markdown Converter Free - Instant Bidirectional Conversion",
    seoDescription: "Convert HTML to Markdown (or Markdown to HTML) in one click. Live preview, sanitized output. 100% browser-based.",
    features: [
      "Bidirectional Markdown ↔ HTML conversion",
      "Live sanitized preview pane",
      "Sample templates for changelogs",
      "One-click copy for both outputs"
    ],
    relatedTools: ["/text-case-converter", "/url-encoder", "/base64-encoder"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/json-xml-converter",
    title: "JSON ↔ XML Converter",
    description: "Transform structured data between JSON and XML with fast-xml-parser, previews, and downloads.",
    icon: <Code2 className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: [
      "json xml converter",
      "xml parser",
      "json payload",
      "api data",
      "sitemap converter"
    ],
    seoTitle: "JSON to XML Converter Free - Transform Data Instantly",
    seoDescription: "Convert JSON to XML (or XML to JSON) in one click. Validation, formatting, download. 100% browser-based, your data stays private.",
    features: [
      "Bidirectional JSON ↔ XML conversion",
      "fast-xml-parser attribute preservation",
      "Size guard with helpful errors",
      "One-click copy or download"
    ],
    relatedTools: ["/csv-json-converter", "/html-markdown-converter", "/text-case-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/text-diff-checker",
    title: "Text Diff Checker",
    description: "Compare drafts, configs, or release notes with inline diff highlights and stats.",
    icon: <GitCompare className="w-8 h-8 text-violet-500" />,
    comingSoon: false,
    keywords: [
      "text diff",
      "compare text online",
      "diff checker",
      "markdown diff",
      "copy review"
    ],
    seoTitle: "Text Diff Checker Free - Compare Texts & Highlight Changes",
    seoDescription: "Spot every difference between two texts instantly. Word, line, character diffs with stats. Download reports. 100% private.",
    features: [
      "Words, lines, and character diff modes",
      "Ignore case or collapse whitespace",
      "Copy or download diff summaries",
      "Privacy-first client-side processing"
    ],
    relatedTools: ["/text-case-converter", "/html-markdown-converter", "/json-xml-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/regex-tester",
    title: "Regex Tester",
    description: "Evaluate regex patterns with instant highlights, capture group tables, and helpful presets.",
    icon: <Code2 className="w-8 h-8 text-amber-500" />,
    comingSoon: false,
    keywords: [
      "regex tester",
      "test regex",
      "regular expression",
      "regex tool",
      "regex highlighter"
    ],
    seoTitle: "Regex Tester Free - Test Patterns & Capture Groups Instantly",
    seoDescription: "Test regex patterns in real-time with match highlighting and capture group tables. Presets for URLs, emails. 100% browser-based.",
    features: [
      "Words, URLs, emails presets",
      "Flag toggles (g, i, m, s, u)",
      "Match highlight + capture group table",
      "Client-side processing only"
    ],
    relatedTools: ["/text-diff-checker", "/html-markdown-converter", "/json-xml-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/uuid-generator",
    title: "UUID Generator",
    description: "Create UUID v1, v4, or v7 identifiers with batch copy/download actions.",
    icon: <Code2 className="w-8 h-8 text-foreground" />,
    comingSoon: false,
    keywords: [
      "uuid generator",
      "uuid v4",
      "uuid v7",
      "generate ids",
      "random guid"
    ],
    seoTitle: "UUID Generator Free - Create v1, v4, v7 UUIDs Instantly | Batch",
    seoDescription: "Generate RFC-compliant UUIDs in one click. v1, v4, v7 versions. Batch create 50 at once. Copy or download. Secure Web Crypto.",
    features: [
      "Supports v1, v4, and v7 versions",
      "Generate up to 50 per batch",
      "Copy or download .txt instantly",
      "Local-only Web Crypto randomness"
    ],
    relatedTools: ["/regex-tester", "/text-diff-checker", "/base64-encoder"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/hash-generator",
    title: "Hash Generator",
    description: "Compute MD5, SHA-1, SHA-256, or SHA-512 digests for text and files with instant copy/download actions.",
    icon: <Code2 className="w-8 h-8 text-foreground" />,
    comingSoon: false,
    keywords: [
      "hash generator",
      "md5 online",
      "sha256",
      "checksum",
      "file hash"
    ],
    seoTitle: "Hash Generator Free - MD5, SHA-256, SHA-512 | Files & Text",
    seoDescription: "Calculate MD5, SHA-1, SHA-256, SHA-512 hashes instantly. Text or file input. Download checksums. 100% browser-based.",
    features: [
      "Toggle MD5, SHA-1, SHA-256, SHA-512",
      "Text area with optional salt",
      "File drop hashing with size guard",
      "Copy or download checksum manifests"
    ],
    relatedTools: ["/uuid-generator", "/regex-tester", "/base64-encoder"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/txt-to-pdf",
    title: "Text to PDF",
    description: "Convert plain text to PDF documents with customizable formatting.",
    icon: <FileText className="w-8 h-8 text-indigo-500" />,
    comingSoon: false,
    keywords: ["text to pdf", "txt to pdf", "convert text to pdf", "text converter", "pdf creator"],
    seoTitle: "Convert Text to PDF Free - Create PDFs from TXT Instantly",
    seoDescription: "Transform plain text to formatted PDF in one click. Custom fonts, margins, page sizes. 100% private - works offline.",
    features: ["Text to PDF conversion", "Customizable formatting", "Page options", "Client-side processing"],
    relatedTools: ["/docx-to-pdf", "/html-to-pdf", "/markdown-to-pdf"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/heic-to-jpg",
    title: "HEIC to JPG",
    description: "Convert HEIC/HEIF photos to standard JPG images without uploading them to a server.",
    icon: <LucideImage className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["heic to jpg", "heic converter", "heif to jpg", "apple photo converter", "image converter"],
    seoTitle: "Convert HEIC to JPG Free - Apple Photos to JPG | No Upload",
    seoDescription: "Convert HEIC/HEIF photos to JPG instantly. Batch process multiple files, preview before download. 100% private browser conversion.",
    features: ["Batch uploads", "Preview before downloading", "Progress tracking", "Runs offline"],
    relatedTools: ["/jpg-to-pdf", "/pdf-to-jpg", "/csv-json-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/docx-to-pdf",
    title: "DOCX to PDF",
    description: "Transform Microsoft Word documents into PDF files without uploading them to a server.",
    icon: <FileText className="w-8 h-8 text-rose-500" />,
    comingSoon: false,
    keywords: ["docx to pdf", "word to pdf", "doc converter", "mammoth", "docx", "pdf"],
    seoTitle: "Convert DOCX to PDF Free - Word to PDF in Seconds | No Upload",
    seoDescription: "Transform Word documents to PDF instantly. Preserve formatting, batch convert multiple files. 100% private - files never uploaded.",
    features: ["Batch uploads", "Progress tracking", "Offline processing", "No file uploads"],
    relatedTools: ["/jpg-to-pdf", "/html-to-pdf", "/csv-json-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/docx-to-text",
    title: "DOCX to Text",
    description: "Extract raw text from DOCX documents using mammoth.js, directly in your browser.",
    icon: <FileText className="w-8 h-8 text-emerald-500" />,
    comingSoon: false,
    keywords: ["docx to text", "extract text docx", "mammoth", "word to text"],
    seoTitle: "Extract Text from DOCX Free - Word to TXT in One Click",
    seoDescription: "Extract raw text from Word documents instantly. Copy to clipboard or download .txt. 100% browser-based, no upload.",
    features: ["Raw text extraction", "Download as .txt", "Copy to clipboard"],
    relatedTools: ["/docx-to-pdf", "/csv-json-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/pdf-to-docx",
    title: "PDF to DOCX",
    description: "Extract text from PDF files into a browser-generated Word-compatible export, with plain-text fallback when DOCX packaging is unavailable.",
    icon: <FileText className="w-8 h-8 text-rose-500" />,
    comingSoon: false,
    keywords: ["pdf to docx", "pdf to word", "convert pdf", "docx converter", "pdf to doc"],
    seoTitle: "Extract PDF Text to Word Free - Browser DOCX or TXT Export",
    seoDescription: "Extract readable text from PDFs into a Word-compatible export entirely in your browser, with a plain-text fallback when needed.",
    features: ["Text extraction", "Word-compatible export", "Plain-text fallback", "No file uploads"],
    relatedTools: ["/pdf-to-jpg", "/docx-to-pdf", "/ocr"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/pdf-to-html",
    title: "PDF to HTML",
    description: "Convert PDF files to HTML markup by extracting content.",
    icon: <FileText className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: ["pdf to html", "convert pdf to html", "extract content", "pdf html converter", "markup extraction"],
    seoTitle: "Convert PDF to HTML Free - Extract Content for Web | Instant",
    seoDescription: "Transform PDFs to HTML markup in seconds. Extract content for web use. Batch processing, 100% browser-based.",
    features: ["Content extraction", "HTML formatting", "Batch processing", "No file uploads"],
    relatedTools: ["/pdf-to-jpg", "/html-to-pdf", "/ocr"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/pdf-to-ppt",
    title: "PDF to PowerPoint",
    description: "Extract PDF text into a presentation-style HTML slide draft for browser review or manual import into slide software.",
    icon: <FileText className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["pdf to ppt", "pdf to powerpoint", "convert pdf to ppt", "presentation", "pdf slides"],
    seoTitle: "Extract PDF to Slide Draft Free - HTML Deck for PowerPoint",
    seoDescription: "Turn PDF page text into an HTML slide draft in your browser. Review locally or import the content into PowerPoint, Google Slides, or Keynote.",
    features: ["HTML slide draft", "Content extraction", "Per-page structure", "No file uploads"],
    relatedTools: ["/pdf-to-jpg", "/pdf-to-html", "/pdf-table-extractor"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/pdf-to-xlsx",
    title: "PDF to Excel",
    description: "Extract table-like PDF text into CSV files that open cleanly in Excel, Google Sheets, or Numbers.",
    icon: <FileText className="w-8 h-8 text-emerald-500" />,
    comingSoon: false,
    keywords: ["pdf to excel", "pdf to xlsx", "convert pdf to excel", "extract tables", "pdf table converter"],
    seoTitle: "Extract PDF Tables to CSV Free - Spreadsheet Ready Export",
    seoDescription: "Extract table-like text from PDFs into CSV files in your browser, then open the results in Excel or any spreadsheet tool.",
    features: ["CSV export", "Table-like text extraction", "Spreadsheet-ready output", "No file uploads"],
    relatedTools: ["/pdf-to-jpg", "/csv-json-converter", "/pdf-table-extractor"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/resize-images",
    title: "Resize Images",
    description: "Resize your images to custom dimensions or predefined presets.",
    icon: <LucideImage className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: ["resize images", "image resize", "change image size", "image dimensions", "image scaler"],
    seoTitle: "Resize Images Free - Custom Dimensions in One Click | No Upload",
    seoDescription: "Resize photos to any size instantly. Presets or custom dimensions, maintain aspect ratio. Batch process. 100% private.",
    features: ["Resize by percentage", "Custom dimensions", "Preset sizes", "Maintain aspect ratio", "Batch processing"],
    relatedTools: ["/image-converter", "/compress-images", "/bmp-tiff-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/compress-images",
    title: "Compress Images",
    description: "Reduce image file sizes while maintaining visual quality.",
    icon: <LucideImage className="w-8 h-8 text-green-500" />,
    comingSoon: false,
    keywords: ["compress images", "image compression", "reduce image size", "optimize images", "image optimizer"],
    seoTitle: "Compress Images Free - Reduce Size 80%+ | Keep Quality",
    seoDescription: "Shrink image files without losing visual quality. Perfect for web optimization. Batch process, 100% browser-based.",
    features: ["Quality control", "Format selection", "Batch processing", "Size reduction metrics"],
    relatedTools: ["/image-converter", "/resize-images", "/bmp-tiff-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/voice-changer",
    title: "Voice Changer",
    description: "Change pitch and speed of audio files to create voice effects.",
    icon: <LucideImage className="w-8 h-8 text-indigo-500" />,
    comingSoon: false,
    keywords: ["voice changer", "change pitch", "change audio speed", "voice effects", "audio transformation"],
    seoTitle: "Voice Changer Free - Modify Pitch & Speed | Create Effects",
    seoDescription: "Transform your voice with pitch and speed controls. Create funny voices, anonymize recordings. 100% private - works offline.",
    features: ["Pitch adjustment", "Speed control", "Voice effects", "Client-side processing"],
    relatedTools: ["/audio-speed-changer", "/remove-silence", "/audio-compressor"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/audio-speed-changer",
    title: "Audio Speed Changer",
    description: "Change the playback speed of audio files while maintaining pitch.",
    icon: <LucideImage className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: ["audio speed changer", "speed up audio", "slow down audio", "change audio speed", "audio tempo"],
    seoTitle: "Change Audio Speed Free - Speed Up or Slow Down | Keep Pitch",
    seoDescription: "Speed up podcasts, slow down lectures. Adjust tempo while keeping pitch intact. 100% browser-based, works offline.",
    features: ["Speed adjustment", "Pitch preservation", "Multiple output formats", "Client-side processing"],
    relatedTools: ["/extract-audio", "/audio-compressor", "/remove-silence"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/remove-silence",
    title: "Remove Silence",
    description: "Remove silence from audio files to create more compact recordings.",
    icon: <LucideImage className="w-8 h-8 text-red-500" />,
    comingSoon: false,
    keywords: ["remove silence", "trim audio", "reduce audio file size", "remove dead air", "audio editing"],
    seoTitle: "Remove Silence from Audio Free - Trim Dead Air Instantly",
    seoDescription: "Strip silent sections from recordings automatically. Adjustable thresholds, preserve speech. 100% private browser tool.",
    features: ["Silence detection", "Adjustable thresholds", "Multiple output formats", "Client-side processing"],
    relatedTools: ["/extract-audio", "/remove-audio", "/audio-compressor"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/audio-compressor",
    title: "Audio Compressor",
    description: "Compress audio files with adjustable compression levels.",
    icon: <LucideImage className="w-8 h-8 text-violet-500" />,
    comingSoon: false,
    keywords: ["audio compressor", "compress audio", "reduce audio file size", "mp3 compressor", "audio optimization"],
    seoTitle: "Compress Audio Files Free - Reduce Size 90% in Seconds | No Upload",
    seoDescription: "Compress audio files instantly with adjustable quality. Reduce MP3, WAV, M4A file size while keeping clarity. 100% private - files never leave your device.",
    features: ["Adjustable compression", "Multiple output formats", "Quality control", "Client-side processing"],
    relatedTools: ["/extract-audio", "/remove-audio", "/wav-mp3-converter", "/m4a-mp3-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/m4a-mp3-converter",
    title: "M4A/MP3 Converter",
    description: "Convert between M4A and MP3 audio formats using FFmpeg.wasm.",
    icon: <LucideImage className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: ["m4a to mp3", "mp3 to m4a", "audio converter", "audio format converter", "ffmpeg"],
    seoTitle: "Convert M4A to MP3 Free - Instant Audio Conversion | No Upload",
    seoDescription: "Convert M4A to MP3 or MP3 to M4A in seconds. Browser-based conversion - your files never leave your device. Free forever, no limits.",
    features: ["M4A to MP3", "MP3 to M4A", "Bitrate control", "Client-side conversion"],
    relatedTools: ["/extract-audio", "/remove-audio", "/wav-mp3-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/wav-mp3-converter",
    title: "WAV/MP3 Converter",
    description: "Convert between WAV and MP3 audio formats using FFmpeg.wasm.",
    icon: <LucideImage className="w-8 h-8 text-yellow-500" />,
    comingSoon: false,
    keywords: ["wav to mp3", "mp3 to wav", "audio converter", "audio format converter", "ffmpeg"],
    seoTitle: "Convert WAV to MP3 Free - High-Quality Audio Conversion | Instant",
    seoDescription: "Convert WAV to MP3 or MP3 to WAV instantly. Preserve audio quality, control bitrate. 100% private - works offline in your browser.",
    features: ["WAV to MP3", "MP3 to WAV", "Bitrate control", "Client-side conversion"],
    relatedTools: ["/extract-audio", "/remove-audio", "/mp4-to-mp3"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/remove-audio",
    title: "Remove Audio",
    description: "Remove the audio track from video files using FFmpeg.wasm.",
    icon: <LucideImage className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["remove audio", "mute video", "audio removal", "video editor", "ffmpeg"],
    seoTitle: "Remove Audio from Video Free - Mute Videos in One Click",
    seoDescription: "Strip audio from any video in seconds. Create silent videos for presentations, social media. No upload needed - works 100% offline.",
    features: ["Audio removal", "Preserve video quality", "Client-side processing", "No uploads"],
    relatedTools: ["/extract-audio", "/video-to-gif", "/mp4-to-mp3"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/extract-audio",
    title: "Extract Audio",
    description: "Extract audio tracks from video files or convert audio formats using FFmpeg.wasm.",
    icon: <LucideImage className="w-8 h-8 text-purple-500" />,
    comingSoon: false,
    keywords: ["extract audio", "audio from video", "video to audio", "audio converter", "ffmpeg"],
    seoTitle: "Extract Audio from Video Free - Get MP3 from Video Instantly",
    seoDescription: "Rip audio from any video file in seconds. Save as MP3, WAV, or M4A. Browser-based extraction - your files stay on your device.",
    features: ["Video to audio", "Audio format conversion", "Multiple output formats", "Client-side processing"],
    relatedTools: ["/mp4-to-mp3", "/video-to-gif", "/remove-audio"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/avi-mkv-to-mp4",
    title: "AVI/MKV to MP4",
    description: "Convert AVI and MKV videos to MP4 format in the browser using FFmpeg.wasm.",
    icon: <LucideImage className="w-8 h-8 text-red-500" />,
    comingSoon: false,
    keywords: ["avi to mp4", "mkv to mp4", "convert video", "video converter", "ffmpeg"],
    seoTitle: "Convert AVI/MKV to MP4 Free - Fast Video Conversion | No Upload",
    seoDescription: "Convert AVI or MKV to MP4 instantly. No software to install, no upload needed. 100% private browser-based conversion.",
    features: ["AVI to MP4", "MKV to MP4", "Client-side conversion", "No file uploads"],
    relatedTools: ["/mp4-to-mp3", "/video-to-gif", "/webm-to-mp4"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/svg-to-png",
    title: "SVG to PNG",
    description: "Convert SVG images to PNG format maintaining quality and transparency.",
    icon: <LucideImage className="w-8 h-8 text-pink-500" />,
    comingSoon: false,
    keywords: ["svg to png", "convert svg", "svg converter", "vector to raster", "image converter"],
    seoTitle: "Convert SVG to PNG Free - Perfect Quality, Instant Download",
    seoDescription: "Convert SVG to high-quality PNG in one click. Preserve transparency, choose custom size. No upload - works offline in your browser.",
    features: ["SVG to PNG conversion", "Transparency preservation", "Batch processing", "No file uploads"],
    relatedTools: ["/image-converter", "/bmp-tiff-converter", "/jpg-to-pdf"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/bmp-tiff-converter",
    title: "BMP/TIFF Converter",
    description: "Convert BMP and TIFF images to PNG or JPG formats.",
    icon: <LucideImage className="w-8 h-8 text-purple-500" />,
    comingSoon: false,
    keywords: ["bmp to png", "tiff to jpg", "bmp converter", "tiff converter", "image format converter"],
    seoTitle: "Convert BMP & TIFF to PNG/JPG Free - Instant Image Conversion",
    seoDescription: "Convert BMP or TIFF to PNG/JPG in seconds. Batch process multiple images. 100% private - files never leave your device.",
    features: ["BMP to PNG/JPG", "TIFF to PNG/JPG", "Batch processing", "No file uploads"],
    relatedTools: ["/image-converter", "/jpg-to-pdf", "/heic-to-jpg"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/image-converter",
    title: "Image Converter",
    description: "Convert between JPG, PNG, and WebP in the browser. Adjust quality and download results.",
    icon: <LucideImage className="w-8 h-8 text-indigo-500" />,
    comingSoon: false,
    keywords: ["jpg to png", "png to jpg", "image converter", "webp to jpg", "image quality"],
    seoTitle: "Convert Images Free - JPG, PNG, WebP in One Click | No Upload",
    seoDescription: "Convert between JPG, PNG, and WebP instantly. Adjust quality, batch process multiple images. 100% private browser conversion.",
    features: ["Batch conversion", "Quality control", "Client-side only", "Preview before download"],
    relatedTools: ["/jpg-to-pdf", "/heic-to-jpg", "/jpg-to-pdf"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/zip-creator",
    title: "ZIP Creator",
    description: "Create ZIP archives from selected files in the browser with JSZip.",
    icon: <Files className="w-8 h-8 text-teal-500" />,
    comingSoon: false,
    keywords: ["zip creator", "create zip", "zip files online", "jszip"],
    seoTitle: "Create ZIP Files Free - Bundle Files Instantly | No Upload",
    seoDescription: "Create ZIP archives in your browser. Bundle multiple files into one download. 100% private - files never leave your device.",
    features: ["Client-side compression", "Preview file list", "No uploads"],
    relatedTools: ["/zip-extractor", "/archive"],
    category: "Compression & Archive",
    isNew: true
  },
  {
    href: "/tar-extractor",
    title: "TAR / GZIP Extractor",
    description: "Extract TAR and GZIP (.tar.gz/.tgz) archives in your browser. Preview and download individual files.",
    icon: <FileText className="w-8 h-8 text-foreground" />,
    comingSoon: false,
    keywords: ["tar extractor", "tar.gz extract", "untar", "extract gzip"],
    seoTitle: "Extract TAR & GZIP Free - Open .tar.gz Files Online | No Upload",
    seoDescription: "Extract TAR and GZIP archives instantly. Preview files, download individually. 100% browser-based - your files stay private.",
    features: ["tar/tar.gz support", "Individual file download", "No upload required"],
    relatedTools: ["/zip-extractor", "/zip-creator"],
    category: "Compression & Archive",
    isNew: true
  },
  {
    href: "/video-to-gif",
    title: "Video to GIF",
    description: "Convert short video clips to animated GIFs using FFmpeg.wasm in the browser.",
    icon: <FileText className="w-8 h-8 text-pink-500" />,
    comingSoon: false,
    keywords: ["video to gif", "gif maker", "ffmpeg wasm"],
    seoTitle: "Convert Video to GIF Free - Make Animated GIFs in Seconds",
    seoDescription: "Turn any video clip into an animated GIF instantly. Adjust FPS, size, quality. No upload - conversion happens in your browser.",
    features: ["FFmpeg.wasm powered", "FPS and width controls", "Runs locally in browser"],
    relatedTools: ["/mp4-to-mp3", "/zip-creator"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/webm-to-mp4",
    title: "WebM ↔ MP4",
    description: "Convert between WebM and MP4 formats using FFmpeg.wasm in your browser.",
    icon: <Music2 className="w-8 h-8 text-amber-500" />,
    comingSoon: false,
    keywords: ["webm to mp4", "mp4 to webm", "video format converter"],
    seoTitle: "Convert WebM to MP4 Free - Instant Video Format Conversion",
    seoDescription: "Convert WebM to MP4 or MP4 to WebM in seconds. Browser-based conversion - no upload, 100% private, works offline.",
    features: ["WebM ↔ MP4", "Runs client-side", "H.264 & VP8/VP9 support"],
    relatedTools: ["/mp4-to-mp3", "/video-compress"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/video-compress",
    title: "Video Compressor",
    description: "Re-encode and compress videos locally using ffmpeg.wasm with a CRF and preset control.",
    icon: <FileText className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["compress video", "ffmpeg wasm", "reduce video size", "video crf"],
    seoTitle: "Compress Video Free - Reduce MP4 Size 80% | No Upload Required",
    seoDescription: "Shrink video files instantly without losing quality. CRF control for perfect balance. 100% private - works offline in your browser.",
    features: ["CRF control", "Preset options (ultrafast/fast/slow)", "Local-only processing"],
    relatedTools: ["/video-to-gif", "/mp4-to-mp3"],
    category: "Media Tools",
    isNew: true
  },
  {
    href: "/video-trim",
    title: "Video Trim & Merge",
    description: "Trim or merge multiple videos locally using FFmpeg.wasm.",
    icon: <Music2 className="w-8 h-8 text-cyan-500" />,
    comingSoon: false,
    keywords: ["trim video", "merge videos", "ffmpeg wasm"],
    seoTitle: "Trim & Merge Videos Free - Edit Clips Online | No Upload",
    seoDescription: "Cut video clips to perfect length, merge multiple videos. Browser-based editing - your files never leave your device.",
    features: ["Trim by timestamps", "Merge multiple files", "Runs locally in browser"],
    relatedTools: ["/video-compress", "/video-to-gif"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/html-to-pdf",
    title: "HTML to PDF Converter",
    description: "Paste markup, adjust page settings, and render a share-ready PDF entirely in your browser.",
    icon: <FileText className="w-8 h-8 text-foreground" />,
    comingSoon: false,
    keywords: [
      "html to pdf",
      "convert html",
      "code to pdf",
      "email html pdf",
      "webpage to pdf"
    ],
    seoTitle: "Convert HTML to PDF Free - Generate PDFs from Code Instantly",
    seoDescription: "Transform HTML markup into polished PDFs in seconds. Live preview, custom page sizes. No upload - works 100% offline.",
    features: [
      "Live HTML preview with syntax highlighting",
      "Supports A4, Letter, and Legal layouts",
      "Sanitized rendering that strips scripts",
      "Client-side export powered by html2canvas + jsPDF"
    ],
    relatedTools: ["/jpg-to-pdf", "/pdf/merge", "/pdf-version-comparison"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/markdown-to-html",
    title: "Markdown to HTML",
    description: "Convert Markdown text to HTML markup directly in your browser.",
    icon: <FileText className="w-8 h-8 text-amber-500" />,
    comingSoon: false,
    keywords: ["markdown to html", "convert markdown", "md to html", "html converter", "markdown processor"],
    seoTitle: "Convert Markdown to HTML Free - Instant MD Conversion Online",
    seoDescription: "Transform Markdown to HTML in real-time. GitHub Flavored Markdown support. No upload - works offline in your browser.",
    features: ["Real-time conversion", "GitHub Flavored Markdown", "HTML output", "Client-side processing"],
    relatedTools: ["/html-to-pdf", "/txt-to-pdf", "/csv-json-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/rotate",
    title: "Rotate PDF",
    description: "Rotate PDF pages to the correct orientation (90, 180, 270 degrees).",
    icon: <RotateCw className="w-8 h-8 text-yellow-500" />,
    comingSoon: false,
    keywords: ["rotate pdf", "fix pdf orientation", "turn pdf pages", "pdf rotation", "flip pdf", "rotate pdf free", "rotate pdf pages"],
    seoTitle: "Rotate PDF Pages Free - Fix Orientation in One Click",
    seoDescription: "Rotate PDF pages 90°, 180°, or 270° instantly. Fix sideways or upside-down scans. Rotate all pages or select specific ones. Free, fast, no upload required.",
    features: ["Multiple rotation angles", "Page-specific rotation", "Batch rotation", "Preview changes"],
    relatedTools: ["/organize", "/reorder", "/delete-pages", "/pdf/split"],
    category: "Organize & Edit"
  },
  {
    href: "/watermark",
    title: "Watermark PDF",
    description: "Add custom text or image watermarks to your PDF documents.",
    icon: <Stamp className="w-8 h-8 text-red-500" />,
    comingSoon: false,
    keywords: ["watermark pdf", "add watermark", "pdf branding", "document protection", "pdf stamp", "watermark pdf free", "add logo to pdf"],
    seoTitle: "Add Watermark to PDF Free - Text & Image Watermarks",
    seoDescription: "Add custom watermarks to PDF in seconds. Text or image, adjust opacity, position anywhere. Protect your documents. Free, unlimited, no sign up needed.",
    features: ["Text & image watermarks", "Custom positioning", "Opacity control", "Rotation options"],
    relatedTools: ["/protect", "/sign", "/page-numbers", "/pdf/compress"],
    category: "Security & Privacy"
  },
  {
    href: "/protect",
    title: "Protect PDF",
    description: "Encrypt your PDFs with a password for enhanced security.",
    icon: <Lock className="w-8 h-8 text-foreground" />,
    comingSoon: false,
    keywords: ["protect pdf", "password pdf", "encrypt pdf", "secure pdf", "pdf security", "password protect pdf free", "lock pdf"],
    seoTitle: "Password Protect PDF Free - Encrypt & Secure Your Files",
    seoDescription: "Add password protection to any PDF in seconds. Military-grade encryption, restrict printing/copying. Free, no upload - encryption happens on your device.",
    features: ["Password encryption", "User permissions", "Print restrictions", "Copy protection"],
    relatedTools: ["/unlock", "/watermark", "/sign", "/pdf/compress"],
    category: "Security & Privacy"
  },
  {
    href: "/unlock",
    title: "Unlock PDF",
    description: "Remove password protection from your PDF files.",
    icon: <Unlock className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["unlock pdf", "remove pdf password", "decrypt pdf", "pdf password remover", "open protected pdf", "unlock pdf free online"],
    seoTitle: "Unlock PDF Free - Remove Password Protection Instantly",
    seoDescription: "Remove PDF password in seconds. Unlock protected PDFs without software. Fast, secure, 100% free. Your file stays on your device - never uploaded.",
    features: ["Password removal", "Quick processing", "Secure unlocking", "No data retention"],
    relatedTools: ["/protect", "/pdf/merge", "/pdf/split", "/pdf/compress"],
    category: "Security & Privacy"
  },
  {
    href: "/delete-pages",
    title: "Delete PDF Pages",
    description: "Remove unwanted pages from your PDF document easily.",
    icon: <Eraser className="w-8 h-8 text-indigo-500 preserve-color" />,
    comingSoon: false,
    keywords: ["delete pdf pages", "remove pdf pages", "extract pdf pages", "pdf page removal", "trim pdf", "remove pages from pdf free"],
    seoTitle: "Delete PDF Pages Free - Remove Unwanted Pages Instantly",
    seoDescription: "Remove any pages from PDF in 3 clicks. Select pages to delete, preview changes, download clean PDF. No watermarks, no limits, 100% private browser processing.",
    features: ["Select specific pages", "Page range deletion", "Preview before deletion", "Instant processing"],
    relatedTools: ["/pdf/split", "/organize", "/reorder", "/pdf/merge"],
    category: "Organize & Edit"
  },
  {
    href: "/reorder",
    title: "Reorder PDF Pages",
    description: "Rearrange the order of pages within your PDF document.",
    icon: <ListOrdered className="w-8 h-8 text-cyan-500 preserve-color" />,
    comingSoon: false,
    keywords: ["reorder pdf pages", "rearrange pdf", "organize pdf pages", "pdf page order", "sort pdf pages"],
    seoTitle: "Reorder PDF Pages Free - Drag & Drop to Rearrange Instantly",
    seoDescription: "Rearrange PDF pages with intuitive drag-and-drop. Visual previews, instant reordering. Free, no limits, 100% browser-based.",
    features: ["Drag & drop interface", "Visual page preview", "Instant reordering", "Download organized PDF"],
    relatedTools: ["/organize", "/delete-pages", "/pdf/split", "/pdf/merge"],
    category: "Organize & Edit"
  },
  {
    href: "/organize",
    title: "Organize PDF",
    description: "Combine reordering and deletion to organize your PDF pages.",
    icon: <ListOrdered className="w-8 h-8 text-cyan-700 preserve-color" />,
    comingSoon: false,
    keywords: ["organize pdf", "pdf organizer", "manage pdf pages", "pdf page management", "restructure pdf", "arrange pdf pages", "pdf page manager"],
    seoTitle: "Organize PDF Pages Free - Reorder, Delete, Arrange Easily",
    seoDescription: "Drag & drop to reorder PDF pages, delete unwanted ones, organize your document perfectly. Visual editor, instant preview, free with no limits.",
    features: ["Page reordering", "Page deletion", "Visual management", "Complete organization"],
    relatedTools: ["/reorder", "/delete-pages", "/pdf/merge", "/pdf/split"],
    category: "Organize & Edit"
  },
  {
    href: "/page-numbers",
    title: "Add Page Numbers",
    description: "Insert customizable page numbers, headers, or footers into your PDF.",
    icon: <PlusCircle className="w-8 h-8 text-amber-500" />,
    comingSoon: false,
    keywords: ["add page numbers", "pdf page numbers", "number pdf pages", "pdf headers footers", "paginate pdf"],
    seoTitle: "Add Page Numbers to PDF Free - Headers & Footers in Seconds",
    seoDescription: "Insert page numbers, headers, or footers to any PDF. Customize format, position, font. Free forever, no upload needed.",
    features: ["Custom numbering formats", "Header & footer options", "Position control", "Font customization"],
    relatedTools: ["/watermark", "/organize", "/pdf/merge", "/sign"],
    category: "Security & Privacy"
  },
  {
    href: "/password-strength",
    title: "Password Strength Checker",
    description: "Analyze the strength of your passwords and get tips to improve them.",
    icon: <Shield className="w-8 h-8 text-red-500" />,
    comingSoon: false,
    keywords: ["password strength", "password checker", "security check", "password analyzer", "strong password"],
    seoTitle: "Password Strength Checker Free - Test Security Instantly",
    seoDescription: "Check if your password is hackable in seconds. Get crack-time estimates and security tips. 100% private - password never sent anywhere.",
    features: ["Instant analysis", "Crack time estimation", "Security tips", "100% client-side privacy"],
    relatedTools: ["/hash-generator", "/protect", "/unlock"],
    category: "Security & Privacy"
  },

  {
    href: "/ocr",
    title: "OCR (Text Recognition)",
    description: "Extract editable text from scanned PDFs and images.",
    icon: <Search className="w-8 h-8 text-green-400" />,
    comingSoon: false,
    keywords: ["ocr pdf", "extract text", "pdf text recognition", "scan to text", "pdf ocr online", "ocr free", "image to text"],
    seoTitle: "Free OCR Online - Extract Text from PDF & Images Instantly",
    seoDescription: "Convert scanned PDFs and images to editable text. AI-powered OCR supports 100+ languages. No upload - your files stay on your device. Fast & accurate.",
    features: ["Text extraction", "Multiple languages", "Image processing", "Editable output"],
    relatedTools: ["/form-filler", "/advanced-ocr", "/medical-analyzer"],
    category: "AI & Analysis"
  },
  {
    href: "/pdf-to-text",
    title: "PDF to Text",
    description: "Extract native text content from PDF files without using OCR.",
    icon: <FileText className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: ["pdf to text", "extract text from pdf", "native text extraction", "pdf text converter", "text extraction"],
    seoTitle: "Extract Text from PDF Free - Copy Text Instantly | No Upload",
    seoDescription: "Extract native text from PDFs in one click. Preserve formatting, copy to clipboard. 100% private browser-based extraction.",
    features: ["Native text extraction", "Fast processing", "Preserve structure", "No file uploads"],
    relatedTools: ["/ocr", "/pdf-to-jpg", "/docx-to-text"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/sign",
    title: "Sign / Annotate PDF",
    description: "Draw, type, or upload your signature and place it on your PDF.",
    icon: <Signature className="w-8 h-8 text-rose-500" />,
    comingSoon: false,
    keywords: ["sign pdf", "pdf signature", "annotate pdf", "digital signature", "pdf signing tool", "sign pdf free", "e-sign pdf"],
    seoTitle: "Sign PDF Free Online - Add Signature in Seconds | No Account",
    seoDescription: "Sign any PDF document instantly. Draw, type, or upload your signature. Add annotations, text, and stamps. Free forever, no account needed, works 100% offline.",
    features: ["Digital signatures", "Drawing tools", "Text annotations", "Signature placement"],
    relatedTools: ["/form-filler", "/protect", "/watermark", "/pdf-digital-signature"],
    category: "Forms & Documents"
  },
  {
    href: "/form-filler",
    title: "PDF Form Filler",
    description: "Add text, checkmarks, or other inputs to any PDF form.",
    icon: <Text className="w-8 h-8 text-lime-500" />,
    comingSoon: false,
    keywords: ["fill pdf form", "pdf form filler", "complete pdf forms", "pdf input", "form completion", "fill pdf online free", "edit pdf form"],
    seoTitle: "Fill PDF Forms Free Online - Complete Any Form Instantly",
    seoDescription: "Fill out any PDF form without Adobe. Add text, checkboxes, signatures. Save completed forms as PDF. 100% free, no account, your data stays private.",
    features: ["Form field detection", "Text input", "Checkbox support", "Form saving"],
    relatedTools: ["/sign", "/ocr", "/protect", "/pdf-form-creator"],
    category: "Forms & Documents"
  },


  {
    href: "/legal-analyzer",
    title: "Legal Document Analyzer",
    description: "AI-powered tool for legal document review and clause extraction.",
    icon: <FileText className="w-8 h-8 text-fuchsia-500" />,
    comingSoon: false,
    keywords: ["legal document analyzer", "contract review", "legal ai", "document analysis", "clause extraction"],
    seoTitle: "AI Legal Document Analyzer - Review Contracts in Seconds Free",
    seoDescription: "AI-powered contract analysis. Extract key clauses, identify risks, and review legal text with clear disclosure that files are uploaded for AI analysis and not stored by easy-pdf.",
    features: ["AI-powered analysis", "Clause extraction", "Risk assessment", "Legal insights"],
    relatedTools: ["/medical-analyzer", "/ocr", "/form-filler"],
    category: "AI & Analysis"
  },
  {
    href: "/medical-analyzer",
    title: "Medical Document Analyzer",
    description: "AI-powered tool for medical document review and key information extraction.",
    icon: <FileHeart className="w-8 h-8 text-red-500" />,
    comingSoon: false,
    keywords: ["medical document analyzer", "medical ai", "health document review", "medical analysis", "patient document"],
    seoTitle: "AI Medical Document Analyzer - Extract Health Records Free",
    seoDescription: "AI-powered medical document review. Extract patient info, diagnoses, medications, and lab findings with clear disclosure that files are uploaded for AI analysis and not stored by easy-pdf.",
    features: ["Medical AI analysis", "Patient data extraction", "Diagnosis identification", "Health insights"],
    relatedTools: ["/legal-analyzer", "/ocr", "/form-filler"],
    category: "AI & Analysis"
  },
  {
    id: 23,
    title: "PDF Metadata Editor",
    description: "Clean up authorship, keywords, and dates without uploading your file.",
    icon: <Settings className="w-8 h-8 text-foreground" />,
    href: "/pdf-metadata-editor",
    keywords: [
      "pdf metadata editor",
      "edit pdf properties",
      "scrub pdf metadata",
      "document title editor",
      "pdf keywords"
    ],
    seoTitle: "Edit PDF Metadata Free - Clean Author & Keywords Instantly",
    seoDescription: "Scrub sensitive metadata from PDFs in one click. Edit title, author, keywords. 100% private - files never uploaded.",
    features: [
      "Runs 100% locally with pdf-lib",
      "One-click scrub for author and keywords",
      "Snapshot + reset flow for safe editing",
      "Audit summary of key metadata fields"
    ],
    relatedTools: ["/protect", "/unlock", "/sign", "/watermark"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 24,
    title: "PDF Bookmark Manager",
    description: "Add, edit, and organize PDF bookmarks and navigation structure",
    icon: <Bookmark className="w-8 h-8 text-blue-500 preserve-color" />,
    href: "/pdf-bookmark-manager",
    keywords: ["pdf bookmark manager", "add pdf bookmarks", "edit bookmarks", "pdf navigation", "organize bookmarks"],
    seoTitle: "Manage PDF Bookmarks Free - Add & Edit Navigation Instantly",
    seoDescription: "Add, edit, organize PDF bookmarks in seconds. Create perfect navigation structure. Free forever, no upload required.",
    features: ["Add custom bookmarks", "Edit existing bookmarks", "Organize bookmark hierarchy", "Export bookmark list"],
    relatedTools: ["/organize", "/reorder", "/page-numbers", "/pdf/split"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 25,
    title: "PDF Table Extractor",
    description: "Extract table-like PDF content and export the recovered data as CSV for spreadsheet tools.",
    icon: <Table className="w-8 h-8 text-green-500" />,
    href: "/pdf-table-extractor",
    keywords: ["pdf table extractor", "extract tables from pdf", "pdf to csv", "pdf to excel", "table extraction"],
    seoTitle: "Extract Tables from PDF Free - CSV Export for Excel",
    seoDescription: "Pull table-like text from PDF files and export the results as CSV in your browser. Review the extracted rows before opening them in Excel or Google Sheets.",
    features: ["Extract tables automatically", "CSV export", "Preview extracted data", "Spreadsheet-friendly output"],
    relatedTools: ["/ocr"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 26,
    title: "PDF Batch Processor",
    description: "Process multiple PDF files at once with various operations like merge, split, compress",
    icon: <Layers className="w-8 h-8 text-purple-500" />,
    href: "/pdf-batch-processor",
    keywords: ["pdf batch processor", "batch pdf processing", "bulk pdf merge", "batch compress pdf", "mass pdf operations"],
    seoTitle: "Process Multiple PDFs Free - Batch Merge, Split, Compress",
    seoDescription: "Handle dozens of PDFs at once. Batch merge, split, compress, watermark. Save hours of manual work. 100% browser-based.",
    features: ["Batch merge multiple PDFs", "Bulk compression", "Mass watermarking", "Batch operations"],
    relatedTools: ["/pdf/merge", "/pdf/compress", "/pdf/split", "/watermark"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 27,
    title: "PDF Form Creator",
    description: "Create interactive PDF forms with various field types including text, checkboxes, and signatures",
    icon: <CheckCircle className="w-8 h-8 text-yellow-500" />,
    href: "/pdf-form-creator",
    keywords: ["pdf form creator", "create pdf forms", "interactive pdf forms", "pdf form builder", "form field creation"],
    seoTitle: "Create PDF Forms Free - Build Interactive Forms in Minutes",
    seoDescription: "Design fillable PDF forms with text fields, checkboxes, dropdowns. No coding needed. Free forever, works offline.",
    features: ["Text input fields", "Checkboxes and radio buttons", "Dropdown menus", "Signature fields"],
    relatedTools: ["/form-filler", "/sign", "/pdf-digital-signature", "/invoice-generator"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 28,
    title: "Advanced OCR with AI",
    description: "Extract text from PDFs and images with AI-assisted OCR, language selection, and confidence reporting.",
    icon: <Search className="w-8 h-8 text-red-500" />,
    href: "/advanced-ocr",
    keywords: ["advanced ocr", "ai ocr", "ocr with ai", "text extraction ai", "intelligent character recognition"],
    seoTitle: "AI-Powered OCR Free - Extract Text with 99% Accuracy",
    seoDescription: "Advanced AI OCR for scanned documents. Multiple language support, confidence scores, and browser-only processing. Files never leave your device.",
    features: ["AI-enhanced text extraction", "Multiple language support", "Page-by-page OCR output", "Confidence scoring"],
    relatedTools: ["/ocr", "/legal-analyzer", "/medical-analyzer"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 29,
    title: "PDF Accessibility Checker",
    description: "Run a local heuristic audit for common PDF accessibility issues and follow-up recommendations.",
    icon: <FileHeart className="w-8 h-8 text-pink-500" />,
    href: "/pdf-accessibility-checker",
    keywords: ["pdf accessibility checker", "wcag compliance", "pdf accessibility", "accessibility audit", "compliance checker"],
    seoTitle: "Check PDF Accessibility Free - Heuristic WCAG Audit",
    seoDescription: "Run a browser-based PDF accessibility audit that flags common WCAG-related issues such as missing tags, weak reading order signals, alt-text gaps, and pages needing manual contrast review.",
    features: ["Tag and title checks", "Alt-text validation", "Reading-order heuristics", "Manual contrast review flags"],
    relatedTools: ["/pdf-redaction", "/pdf-version-comparison", "/pdf-digital-signature", "/sign"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 30,
    title: "PDF Digital Signature",
    description: "Add a visible signature stamp with embedded signer metadata and local validation",
    icon: <Shield className="w-8 h-8 text-blue-500" />,
    href: "/pdf-digital-signature",
    keywords: ["pdf digital signature", "visible signature pdf", "signature metadata", "certificate information", "signature validation"],
    seoTitle: "Add Signature Stamp to PDF Free - Visible Signer Metadata",
    seoDescription: "Create a visible PDF signature block with signer metadata and local validation. 100% private - runs in your browser.",
    features: ["Visible signer stamp", "Embedded signer metadata", "Local validation", "Browser-only processing"],
    relatedTools: ["/sign", "/protect", "/unlock", "/form-filler"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 31,
    title: "PDF Redaction Tool",
    description: "Flatten and redact sensitive PDF content locally with text search, manual areas, and metadata cleanup",
    icon: <EyeOff className="w-8 h-8 text-indigo-500" />,
    href: "/pdf-redaction",
    keywords: ["pdf redaction", "redact pdf", "remove sensitive information", "metadata cleaning", "secure deletion"],
    seoTitle: "Redact PDF Free - Permanently Remove Sensitive Info | Secure",
    seoDescription: "Search, mark, and flatten redacted PDF pages entirely in your browser. Clean metadata and keep every file private.",
    features: ["Search-based redaction", "Manual redaction areas", "Metadata cleaning", "Flattened output"],
    relatedTools: ["/protect", "/unlock", "/pdf-accessibility-checker", "/sign"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 32,
    title: "PDF Version Comparison",
      description: "Compare two PDF revisions locally and review text, metadata, page count, and layout changes with exportable reports",
    icon: <GitCompare className="w-8 h-8 text-orange-500" />,
    href: "/pdf-version-comparison",
      keywords: ["pdf comparison", "compare pdf versions", "pdf diff", "metadata comparison", "version tracking"],
    seoTitle: "Compare PDF Versions Free - Spot Every Change Instantly",
      seoDescription: "Compare PDF revisions in your browser with text, metadata, and page-layout analysis. Export structured reports and keep every file private.",
    features: [
        "Page-by-page text difference summaries",
        "Metadata, page-count, and layout change detection",
      "Tabbed interface for uploads, diffs, and statistics",
      "JSON report export for compliance and QA"
    ],
    relatedTools: ["/pdf-accessibility-checker", "/ocr", "/legal-analyzer", "/medical-analyzer"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 33,
    title: "PDF Annotation Collaboration",
    description: "Build a local PDF review workspace with annotations, replies, reviewer roles, and exportable review data.",
    icon: <MessageSquare className="w-8 h-8 text-cyan-500" />,
    href: "/pdf-annotation-collaboration",
    keywords: ["pdf annotation collaboration", "collaborative annotations", "team pdf review", "shared comments", "review workflows"],
    seoTitle: "PDF Review Workspace Free - Annotate, Track, and Export",
    seoDescription: "Create a local PDF review workspace with comments, replies, reviewer roles, annotated PDF export, and JSON review records.",
    features: ["Local review workspace", "Comment threads", "Export annotations", "Review workflows"],
    relatedTools: ["/sign", "/form-filler", "/pdf-digital-signature", "/pdf-batch-processor"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    href: "/invoice-generator",
    title: "PDF Invoice Generator",
    description: "Create professional invoices with GST support, multiple currencies, and customizable templates.",
    icon: <Calculator className="w-8 h-8 text-green-500" />,
    comingSoon: false,
    keywords: ["pdf invoice generator", "create invoice", "invoice maker", "business invoice", "gst invoice", "professional invoice"],
    seoTitle: "Create PDF Invoice Free - Professional Templates | GST Ready",
    seoDescription: "Generate professional invoices in seconds. GST support, multiple currencies, customizable templates. Free forever, no sign up.",
    features: ["Professional invoice templates", "GST and tax calculations", "Multiple currency support", "Client and company management"],
    relatedTools: ["/form-filler", "/sign", "/watermark"],
    category: "Business Tools",
    isNew: true
  },
  {
    href: "/qr-generator",
    title: "QR Code Generator",
    description: "Generate QR codes for URLs, text, WiFi, contact cards, and more. Export as PNG or PDF.",
    icon: <QrCode className="w-8 h-8 text-purple-500" />,
    comingSoon: false,
    keywords: ["qr code generator", "qr code maker", "wifi qr code", "vcard qr code", "url qr code", "qr code pdf", "free qr generator"],
    seoTitle: "Free QR Code Generator - Create & Download QR Codes Instantly",
    seoDescription: "Generate QR codes for URLs, WiFi, vCards, text in seconds. Download as PNG or PDF. Custom sizes, 100% free, no sign up, works offline in your browser.",
    features: ["Multiple QR code types", "Customizable size and quality", "WiFi and vCard support", "PNG and PDF export"],
    relatedTools: ["/watermark", "/pdf/merge", "/form-filler"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/qr-scanner",
    title: "QR Code Scanner",
    description: "Scan QR codes directly from your camera or upload an image.",
    icon: <QrCode className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: ["qr scanner", "qr code reader", "scan qr code", "barcode scanner", "read qr code"],
    seoTitle: "Scan QR Code Free - Camera or Upload | Works Offline",
    seoDescription: "Scan QR codes instantly using camera or image upload. 100% private - data never sent anywhere. Works offline in your browser.",
    features: ["Camera scanning", "Image file scanning", "Works offline", "100% client-side privacy"],
    relatedTools: ["/qr-generator", "/jpg-to-pdf", "/pdf-to-jpg"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/barcode-generator",
    title: "Barcode Generator",
    description: "Create custom barcodes (UPC, EAN, CODE128) for products or inventory.",
    icon: <QrCode className="w-8 h-8 text-indigo-500" />, // Reusing QrCode icon for now, or use a different one if available
    comingSoon: false,
    keywords: ["barcode generator", "barcode maker", "upc generator", "ean generator", "code128"],
    seoTitle: "Generate Barcodes Free - UPC, EAN, Code128 | Download PNG/SVG",
    seoDescription: "Create product barcodes in seconds. UPC, EAN, Code128, and more. Customize size, download PNG or SVG. Free forever, no limits.",
    features: ["Supports multiple formats", "Customizable size and color", "SVG and PNG export", "Instant preview"],
    relatedTools: ["/qr-generator", "/qr-scanner"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/certificate-generator",
    title: "Certificate Generator",
    description: "Create professional certificates for courses, training, achievements, and more with customizable templates.",
    icon: <Award className="w-8 h-8 text-yellow-500" />,
    comingSoon: false,
    keywords: ["certificate generator", "certificate maker", "course certificate", "training certificate", "achievement certificate"],
    seoTitle: "Create Certificates Free - Professional PDF Templates | Instant",
    seoDescription: "Design professional certificates in minutes. Course, training, achievement templates. Auto-generate IDs. Free forever, no sign up.",
    features: ["Multiple certificate templates", "Customizable colors and styles", "Professional layouts", "Automatic certificate IDs"],
    relatedTools: ["/sign", "/watermark", "/form-filler"],
    category: "Business Tools",
    isNew: true
  },
  {
    href: "/portfolio-creator",
    title: "Portfolio Creator",
    description: "Create professional PDF portfolios with customizable sections for experience, education, skills, and projects.",
    icon: <Briefcase className="w-8 h-8 text-blue-500 preserve-color" />,
    comingSoon: false,
    keywords: ["portfolio creator", "pdf portfolio", "professional portfolio", "resume builder", "cv maker"],
    seoTitle: "Create PDF Portfolio Free - Professional Templates | Instant Download",
    seoDescription: "Build stunning PDF portfolios in minutes. Experience, education, skills, projects sections. Professional templates, free forever.",
    features: ["Professional portfolio templates", "Multiple customizable sections", "Experience and education tracking", "Skills and projects showcase"],
    relatedTools: ["/certificate-generator", "/invoice-generator", "/form-filler"],
    category: "Business Tools",
    isNew: true
  },
  {
    href: "/report-generator",
    title: "Report Generator",
    description: "Create professional business reports with sections, metrics, charts, and recommendations.",
    icon: <FileText className="w-8 h-8 text-indigo-500 preserve-color" />,
    comingSoon: false,
    keywords: ["report generator", "business report", "pdf report", "professional report", "report maker"],
    seoTitle: "Create Business Reports Free - Professional PDF Templates",
    seoDescription: "Generate polished business reports in minutes. Metrics, charts, recommendations. Professional formatting, free forever.",
    features: ["Multiple report templates", "Key metrics dashboard", "Customizable sections", "Professional formatting"],
    relatedTools: ["/portfolio-creator", "/invoice-generator", "/certificate-generator"],
    category: "Business Tools",
    isNew: true
  },
  {
    href: "/xlsx-to-csv",
    title: "XLSX to CSV",
    description: "Convert Excel spreadsheets (XLSX) to CSV format instantly in your browser.",
    icon: <Table className="w-8 h-8 text-green-600" />,
    comingSoon: false,
    keywords: ["xlsx to csv", "excel to csv", "convert excel", "spreadsheet converter", "xlsx converter"],
    seoTitle: "Convert Excel to CSV Free - XLSX to CSV in One Click | No Upload",
    seoDescription: "Transform Excel spreadsheets to CSV instantly. 100% private - files never leave your browser. Fast, secure, unlimited conversions.",
    features: ["Convert XLSX to CSV", "Client-side processing", "No file uploads", "Fast conversion"],
    relatedTools: ["/csv-to-xlsx", "/pdf-to-xlsx", "/csv-json-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/csv-to-xlsx",
    title: "CSV to XLSX",
    description: "Convert CSV files to Excel (XLSX) spreadsheets instantly in your browser.",
    icon: <Table className="w-8 h-8 text-emerald-600" />,
    comingSoon: false,
    keywords: ["csv to xlsx", "csv to excel", "convert csv", "spreadsheet converter", "csv converter"],
    seoTitle: "Convert CSV to Excel Free - CSV to XLSX Instantly | No Upload",
    seoDescription: "Transform CSV files to Excel spreadsheets in one click. 100% private - files stay on your device. Unlimited conversions, free forever.",
    features: ["Convert CSV to XLSX", "Client-side processing", "No file uploads", "Fast conversion"],
    relatedTools: ["/xlsx-to-csv", "/pdf-to-xlsx", "/csv-json-converter"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/metadata-extractor",
    title: "Metadata Extractor",
    description: "View hidden metadata (EXIF, XMP) from images and PDF documents.",
    icon: <Search className="w-8 h-8 text-cyan-500" />,
    comingSoon: false,
    keywords: ["metadata extractor", "exif viewer", "pdf metadata", "image metadata", "read exif"],
    seoTitle: "Extract Metadata Free - View EXIF, PDF Properties Instantly",
    seoDescription: "Reveal hidden metadata from images and PDFs. See EXIF data, camera settings, author info. 100% private - files never uploaded.",
    features: ["View Image EXIF data", "View PDF properties", "100% client-side", "Supports JPG, PNG, PDF"],
    relatedTools: ["/pdf-metadata-editor", "/pdf-to-jpg"],
    category: "Security & Privacy",
    isNew: true
  },
  {
    href: "/html-minifier",
    title: "HTML Minifier",
    description: "Compress HTML code by removing whitespace and comments.",
    icon: <Code2 className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["html minifier", "minify html", "compress html", "html optimizer", "clean html"],
    seoTitle: "Minify HTML Free - Compress Code 60%+ in Seconds",
    seoDescription: "Shrink HTML files instantly. Remove whitespace, comments, optimize code. One click to copy minified code. Free forever.",
    features: ["Removes comments", "Collapses whitespace", "Instant results", "Copy to clipboard"],
    relatedTools: ["/html-to-pdf", "/markdown-to-html"],
    category: "Web Tools",
    isNew: true
  },
  {
    href: "/css-minifier",
    title: "CSS Minifier",
    description: "Compress CSS code to reduce file size.",
    icon: <Code2 className="w-8 h-8 text-blue-400" />,
    comingSoon: false,
    keywords: ["css minifier", "minify css", "compress css", "css optimizer", "clean css"],
    seoTitle: "Minify CSS Free - Compress Stylesheets 50%+ Instantly",
    seoDescription: "Shrink CSS files in one click. Remove whitespace, comments, optimize code. Faster page loads. Free forever, no limits.",
    features: ["Removes comments", "Collapses whitespace", "Instant results", "Copy to clipboard"],
    relatedTools: ["/html-minifier", "/js-minifier"],
    category: "Web Tools",
    isNew: true
  },
  {
    href: "/js-minifier",
    title: "JS Minifier",
    description: "Compress JavaScript code to reduce file size.",
    icon: <Code2 className="w-8 h-8 text-yellow-400" />,
    comingSoon: false,
    keywords: ["js minifier", "minify js", "compress javascript", "js optimizer", "clean js"],
    seoTitle: "Minify JavaScript Free - Compress JS Code 60%+ Instantly",
    seoDescription: "Shrink JavaScript files in seconds. Remove whitespace, comments, optimize code. Faster websites. Free, unlimited usage.",
    features: ["Removes comments", "Collapses whitespace", "Instant results", "Copy to clipboard"],
    relatedTools: ["/css-minifier", "/html-minifier"],
    category: "Web Tools",
    isNew: true
  },
  {
    href: "/aes-encrypt",
    title: "AES Encryption",
    description: "Encrypt and decrypt text using AES-256.",
    icon: <Lock className="w-8 h-8 text-purple-600" />,
    comingSoon: false,
    keywords: ["aes encryption", "encrypt text", "decrypt text", "aes-256", "secure message"],
    seoTitle: "Encrypt Text with AES-256 Free - Military-Grade Security",
    seoDescription: "Encrypt sensitive text with unbreakable AES-256. Decrypt instantly with your password. 100% private - data never leaves your browser.",
    features: ["AES-256 encryption", "Instant decryption", "Client-side security", "No data storage"],
    relatedTools: ["/password-strength", "/hash-generator"],
    category: "Security & Privacy",
    isNew: true
  },
  {
    href: "/rsa-generator",
    title: "RSA Key Generator",
    description: "Generate secure RSA public and private key pairs.",
    icon: <Key className="w-8 h-8 text-amber-600" />,
    comingSoon: false,
    keywords: ["rsa generator", "rsa keys", "public private key", "generate rsa", "web crypto"],
    seoTitle: "Generate RSA Keys Free - 2048/4096 Bit | Download PEM",
    seoDescription: "Create secure RSA key pairs instantly. 2048 or 4096 bit. Download PEM format for OpenSSL. 100% private - keys never sent anywhere.",
    features: ["2048/4096 bit keys", "PEM format export", "Client-side generation", "No server storage"],
    relatedTools: ["/aes-encrypt", "/hash-generator"],
    category: "Security & Privacy",
    isNew: true
  },
  {
    href: "/jwt-decoder",
    title: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens (JWT).",
    icon: <Shield className="w-8 h-8 text-pink-500" />,
    comingSoon: false,
    keywords: ["jwt decoder", "decode jwt", "json web token", "jwt debugger", "read jwt"],
    seoTitle: "Decode JWT Free - Inspect JSON Web Tokens Instantly",
    seoDescription: "Decode and inspect JWTs in one click. View header, payload, claims, expiration. 100% private - token never sent anywhere.",
    features: ["Decode Header & Payload", "View expiration times", "Format JSON output", "Client-side only"],
    relatedTools: ["/base64-encoder", "/json-xml-converter"],
    category: "Security & Privacy",
    isNew: true
  },
  {
    href: "/markdown-previewer",
    title: "Markdown Previewer",
    description: "Real-time Markdown to HTML preview.",
    icon: <FileText className="w-8 h-8 text-foreground" />,
    comingSoon: false,
    keywords: ["markdown preview", "md viewer", "markdown editor", "readme editor", "live markdown"],
    seoTitle: "Preview Markdown Free - Real-Time Editor | GitHub Flavored",
    seoDescription: "Write and preview Markdown instantly. GitHub Flavored Markdown support, live HTML rendering. Perfect for README files.",
    features: ["Real-time preview", "GFM support", "HTML export", "Split view"],
    relatedTools: ["/markdown-to-html", "/html-to-markdown"],
    category: "Web Tools",
    isNew: true
  },
  {
    href: "/number-base-converter",
    title: "Number Base Converter",
    description: "Convert numbers between Binary, Octal, Decimal, and Hexadecimal.",
    icon: <Calculator className="w-8 h-8 text-indigo-500" />,
    comingSoon: false,
    keywords: ["base converter", "binary converter", "hex converter", "decimal to binary", "hex to decimal"],
    seoTitle: "Convert Number Bases Free - Binary, Hex, Decimal Instantly",
    seoDescription: "Convert between Binary, Octal, Decimal, Hexadecimal in one click. Instant results, copy to clipboard. Perfect for developers.",
    features: ["Binary, Octal, Decimal, Hex", "Instant conversion", "Copy to clipboard", "Bidirectional"],
    relatedTools: ["/calculator", "/unit-converter"],
    category: "Utility Converters",
    isNew: true
  },
  {
    href: "/unit-converter",
    title: "Unit Converter",
    description: "Convert between different units of measurement (Length, Weight, Volume, etc).",
    icon: <Calculator className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["unit converter", "measurement converter", "length converter", "weight converter"],
    seoTitle: "Unit Converter Free - Length, Weight, Volume & More | Instant",
    seoDescription: "Convert between any units instantly. Length, weight, volume, temperature, speed, and more. Clean interface, accurate results.",
    features: ["Multiple categories", "Real-time conversion", "Standard units", "Easy to use"],
    relatedTools: ["/currency-converter", "/number-base-converter"],
    category: "Utility Converters",
    isNew: true
  },
  {
    href: "/currency-converter",
    title: "Currency Converter",
    description: "Convert between major world currencies with approximate rates.",
    icon: <Calculator className="w-8 h-8 text-green-600" />,
    comingSoon: false,
    keywords: ["currency converter", "exchange rates", "money converter", "usd to eur"],
    seoTitle: "Currency Converter Free - Convert World Currencies Instantly",
    seoDescription: "Convert between major world currencies in one click. USD, EUR, GBP, and more. Works offline, instant calculations.",
    features: ["Major currencies supported", "Approximate rates", "Offline capable", "Instant calculation"],
    relatedTools: ["/unit-converter", "/number-base-converter"],
    category: "Utility Converters",
    isNew: true
  },
  {
    href: "/timezone-converter",
    title: "Timezone Converter",
    description: "Convert time between different global timezones.",
    icon: <Globe className="w-8 h-8 text-blue-400" />,
    comingSoon: false,
    keywords: ["timezone converter", "world clock", "time difference", "utc converter"],
    seoTitle: "Timezone Converter Free - World Clock & Time Difference",
    seoDescription: "Convert time between any timezone instantly. Plan meetings, schedule calls across time zones. DST-aware, always accurate.",
    features: ["Global timezones", "Date and time selection", "DST aware", "Simple interface"],
    relatedTools: ["/unit-converter", "/currency-converter"],
    category: "Utility Converters",
    isNew: true
  },
  {
    href: "/color-converter",
    title: "Color Converter",
    description: "Convert colors between HEX, RGB, HSL, and CMYK formats.",
    icon: <Palette className="w-8 h-8 text-purple-500" />,
    comingSoon: false,
    keywords: ["color converter", "hex to rgb", "rgb to hex", "hsl converter", "cmyk converter"],
    seoTitle: "Color Converter Free - HEX to RGB, HSL, CMYK | One Click",
    seoDescription: "Convert colors between HEX, RGB, HSL, CMYK instantly. Live preview, copy codes. Perfect for designers and developers.",
    features: ["HEX, RGB, HSL, CMYK", "Color preview", "Copy to clipboard", "Dark/Light mode detection"],
    relatedTools: ["/image-converter", "/css-minifier"],
    category: "Utility Converters",
    isNew: true
  },
  {
    href: "/url-shortener",
    title: "URL Shortener",
    description: "Create short links for your long URLs (Local Demo).",
    icon: <Link className="w-8 h-8 text-indigo-500" />,
    comingSoon: false,
    keywords: ["url shortener", "link shortener", "short link", "tiny url"],
    seoTitle: "Shorten URLs Free - Create Short Links | 100% Private",
    seoDescription: "Create short links instantly. All data stored locally in your browser. No tracking, no account needed, 100% private.",
    features: ["Local storage", "Privacy focused", "Instant generation", "Link management"],
    relatedTools: ["/qr-generator", "/url-encoder"],
    category: "Web Tools",
    isNew: true
  },
  {
    href: "/steganography",
    title: "Steganography",
    description: "Hide secret text messages inside PNG images.",
    icon: <EyeOff className="w-8 h-8 text-foreground" />,
    comingSoon: false,
    keywords: ["steganography", "hide text in image", "secret message", "image encryption"],
    seoTitle: "Hide Text in Images Free - Steganography Tool | Undetectable",
    seoDescription: "Embed secret messages inside PNG images invisibly. Encode and decode hidden text. 100% private - image never uploaded.",
    features: ["Hide text in images", "LSB algorithm", "Secure & private", "No server upload"],
    relatedTools: ["/aes-encrypt", "/file-checksum"],
    category: "Security & Privacy",
    isNew: true
  },
  {
    href: "/image-filters",
    title: "Image Filters",
    description: "Apply artistic filters and adjustments to your photos.",
    icon: <Sliders className="w-8 h-8 text-pink-500" />,
    comingSoon: false,
    keywords: ["image filters", "photo effects", "instagram filters", "image brightness", "grayscale"],
    seoTitle: "Apply Image Filters Free - Brightness, Contrast & Effects",
    seoDescription: "Enhance photos with filters in one click. Brightness, contrast, saturation, sepia, grayscale. Real-time preview, free forever.",
    features: ["Brightness/Contrast", "Artistic filters", "Real-time preview", "High quality export"],
    relatedTools: ["/image-crop", "/image-rotator"],
    category: "Image Editing",
    isNew: true
  },
  {
    href: "/image-text-overlay",
    title: "Add Text to Image",
    description: "Overlay text on your images with custom fonts and colors.",
    icon: <Type className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: ["add text to image", "image caption", "photo text", "write on image"],
    seoTitle: "Add Text to Image Free - Custom Fonts & Colors | No Upload",
    seoDescription: "Overlay text on photos instantly. Custom fonts, colors, positioning. Create memes, captions, watermarks. 100% private.",
    features: ["Custom fonts", "Color selection", "Opacity control", "Drag positioning"],
    relatedTools: ["/image-watermark", "/image-drawing"],
    category: "Image Editing",
    isNew: true
  },
  {
    href: "/image-drawing",
    title: "Draw on Image",
    description: "Annotate your images with freehand drawing.",
    icon: <PenTool className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["draw on image", "annotate image", "photo drawing", "highlight image"],
    seoTitle: "Draw on Image Free - Annotate Photos with Freehand Tools",
    seoDescription: "Draw, highlight, annotate images directly in browser. Custom colors, brush sizes. Perfect for feedback and markup. Free forever.",
    features: ["Freehand drawing", "Custom colors", "Brush size control", "Instant download"],
    relatedTools: ["/image-text-overlay", "/image-crop"],
    category: "Image Editing",
    isNew: true
  },
  {
    href: "/image-watermark",
    title: "Image Watermark",
    description: "Protect your images with a custom logo or watermark.",
    icon: <Stamp className="w-8 h-8 text-purple-500" />,
    comingSoon: false,
    keywords: ["image watermark", "add logo to photo", "copyright image", "watermark tool"],
    seoTitle: "Add Watermark to Image Free - Logo Overlay | Protect Photos",
    seoDescription: "Add logo or watermark to photos in seconds. Adjust transparency, size, position. Protect your work. 100% browser-based.",
    features: ["Image overlay", "Transparency control", "Resize & Position", "Single-image workflow"],
    relatedTools: ["/image-text-overlay", "/protect"],
    category: "Image Editing",
    isNew: true
  },
  {
    href: "/remove-background",
    title: "Remove Background",
    description: "Automatically remove background from images using AI.",
    icon: <Eraser className="w-8 h-8 text-purple-500" />,
    comingSoon: false,
    keywords: ["remove background", "transparent background", "background eraser", "ai background remover", "png maker"],
    seoTitle: "Remove Background Free - AI-Powered | Instant Transparent PNG",
    seoDescription: "Erase image backgrounds with AI in one click. Get transparent PNGs instantly. 100% private - images never uploaded.",
    features: ["AI-powered removal", "Instant processing", "Transparent PNG output", "100% private"],
    relatedTools: ["/image-crop", "/image-filters"],
    category: "Image Editing",
    isNew: true
  },
  {
    href: "/face-blur",
    title: "Face Blur",
    description: "Automatically detect and blur faces in photos.",
    icon: <EyeOff className="w-8 h-8 text-indigo-500" />,
    comingSoon: false,
    keywords: ["face blur", "blur faces", "hide faces", "privacy blur", "anonymize photo"],
    seoTitle: "Blur Faces in Photos Free - AI Auto-Detection | Privacy Tool",
    seoDescription: "Automatically detect and blur faces with AI. Protect privacy in photos instantly. 100% browser-based - images never uploaded.",
    features: ["AI face detection", "Automatic blurring", "Privacy protection", "100% local processing"],
    relatedTools: ["/remove-background", "/image-filters"],
    category: "Image Editing",
    isNew: true
  },
  {
    href: "/image-crop",
    title: "Crop Image",
    description: "Crop your images to exact dimensions or aspect ratios.",
    icon: <Crop className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["crop image", "image cropper", "photo crop", "trim image"],
    seoTitle: "Crop Images Free - Custom Dimensions & Aspect Ratios",
    seoDescription: "Crop photos to perfect size instantly. Custom dimensions, preset aspect ratios, grid overlay. High quality export, free forever.",
    features: ["Custom aspect ratios", "Freeform cropping", "Grid overlay", "High quality export"],
    relatedTools: ["/resize-images", "/image-rotator"],
    category: "Image Editing",
    isNew: true
  },
  {
    href: "/image-cropper",
    title: "Image Cropper",
    description: "Crop and resize images online.",
    icon: <Crop className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["image cropper", "crop picture", "photo cropper"],
    seoTitle: "Image Cropper Free - Resize & Crop Pictures Online",
    seoDescription: "Crop, resize, and rotate images in your browser. Simple interface, high quality output. Free forever, no upload needed.",
    features: ["Crop images", "Resize", "Rotate"],
    relatedTools: ["/image-crop", "/resize-images"],
    category: "Image Editing",
    isNew: true
  },
  {
    href: "/image-rotator",
    title: "Rotate Image",
    description: "Rotate images 90, 180, or 270 degrees.",
    icon: <RotateCw className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: ["rotate image", "flip image", "turn photo"],
    seoTitle: "Rotate Images Free - Fix Photo Orientation in One Click",
    seoDescription: "Rotate photos 90°, 180°, 270° instantly. Flip horizontal or vertical. Fix wrong orientation. Free forever, no upload.",
    features: ["90/180/270 degree rotation", "Flip horizontal/vertical", "Batch processing"],
    relatedTools: ["/image-crop", "/resize-images"],
    category: "Image Editing",
    isNew: true
  },
  {
    href: "/file-checksum",
    title: "File Checksum",
    description: "Verify file integrity with MD5, SHA-1, and SHA-256 hashes.",
    icon: <Shield className="w-8 h-8 text-green-500" />,
    comingSoon: false,
    keywords: ["file checksum", "verify file", "md5 check", "sha256 check"],
    seoTitle: "File Checksum Calculator Free - MD5, SHA-1, SHA-256",
    seoDescription: "Verify file integrity with MD5, SHA-1, SHA-256 hashes instantly. Compare checksums, detect corruption. 100% browser-based.",
    features: ["MD5, SHA-1, SHA-256", "Verify file integrity", "Client-side calculation"],
    relatedTools: ["/hash-generator", "/aes-encrypt"],
    category: "Security & Privacy",
    isNew: true
  },
  {
    href: "/ppt-to-pdf",
    title: "PPT to PDF",
    description: "Understand the browser-side limitations of PPT/PPTX to PDF conversion and use recommended alternative export workflows.",
    icon: <FileText className="w-8 h-8 text-red-500" />,
    comingSoon: false,
    keywords: ["ppt to pdf", "powerpoint to pdf", "convert ppt"],
    seoTitle: "PPT to PDF Limitations - Practical Export Alternatives",
    seoDescription: "Review why reliable PowerPoint-to-PDF conversion is not available in this browser-only workflow and follow recommended export options instead.",
    features: ["PPT/PPTX file validation", "Browser limitation guidance", "Alternative export steps"],
    relatedTools: ["/pdf-to-ppt", "/docx-to-pdf"],
    category: "Convert & Create",
    isNew: true
  }
];