// Tool data with string icon names for dynamic loading
import React from "react";
import { FileText, Split, Minimize2, RotateCw, Stamp, Lock, Unlock, Text, ListOrdered, Eraser, PlusCircle, Signature, FileBadge2, Image as LucideImage, Search, FileHeart, Settings, Bookmark, Table, Layers, CheckCircle, Shield, EyeOff, GitCompare, MessageSquare, Calculator, QrCode, Award, Briefcase } from "lucide-react";

export const toolsData = [
  {
    href: "/merge",
    title: "Merge PDF",
    description: "Combine multiple PDF files into one seamless document.",
    icon: "Merge",
    iconClassName: "w-8 h-8 text-blue-500",
    comingSoon: false,
    keywords: ["merge pdf", "combine pdf", "join pdf files", "pdf merger", "unite pdf"],
    seoTitle: "Free PDF Merger - Combine Multiple PDFs Online",
    seoDescription: "Merge multiple PDF files into one document for free. Fast, secure, and works entirely in your browser. No file size limits or registration required.",
    features: ["Drag & drop multiple files", "Reorder before merging", "No file size limits", "100% secure processing"],
    relatedTools: ["/split", "/organize", "/compress"],
    category: "Organize & Edit"
  },
  {
    href: "/split",
    title: "Split PDF",
    description: "Extract specific pages or split a PDF into multiple files.",
    icon: <Split className="w-8 h-8 text-green-500" />,
    comingSoon: false,
    keywords: ["split pdf", "extract pdf pages", "separate pdf", "divide pdf", "pdf splitter"],
    seoTitle: "Free PDF Splitter - Extract Pages from PDF Online",
    seoDescription: "Split PDF files into separate documents or extract specific pages. Free online tool with secure browser-based processing.",
    features: ["Extract specific pages", "Split by page ranges", "Preview before splitting", "Download as ZIP"],
    relatedTools: ["/merge", "/delete-pages", "/organize"],
    category: "Organize & Edit"
  },
  {
    href: "/compress",
    title: "Compress PDF",
    description: "Reduce PDF file size for easier sharing and storage.",
    icon: <Minimize2 className="w-8 h-8 text-purple-500" />,
    comingSoon: false,
    keywords: ["compress pdf", "reduce pdf size", "optimize pdf", "shrink pdf", "pdf compressor"],
    seoTitle: "Free PDF Compressor - Reduce PDF File Size Online",
    seoDescription: "Compress PDF files to reduce size while maintaining quality. Free online PDF compression tool with multiple optimization levels.",
    features: ["Multiple compression levels", "Quality preservation", "Batch processing", "Size preview"],
    relatedTools: ["/merge", "/split", "/watermark", "/protect"],
    category: "Security & Privacy"
  },
  {
    href: "/jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert your JPG, PNG, or other images into a PDF document.",
    icon: <LucideImage alt="JPG to PDF Icon" className="w-8 h-8 text-pink-500" />,
    comingSoon: false,
    keywords: ["jpg to pdf", "png to pdf", "image to pdf", "convert images", "photo to pdf"],
    seoTitle: "Free JPG to PDF Converter - Convert Images to PDF Online",
    seoDescription: "Convert JPG, PNG, and other images to PDF format. Free online converter with batch processing and custom page sizing.",
    features: ["Multiple image formats", "Batch conversion", "Custom page sizes", "Image ordering"],
    relatedTools: ["/pdf-to-jpg", "/merge", "/compress"],
    category: "Convert & Create"
  },
  
  {
    href: "/pdf-to-jpg",
    title: "PDF to JPG",
    description: "Convert PDF pages into high-quality JPG image files.",
    icon: <FileText className="w-8 h-8 text-teal-500" />,
    comingSoon: false,
    keywords: ["pdf to jpg", "pdf to png", "convert pdf to image", "pdf to photo", "extract images"],
    seoTitle: "Free PDF to JPG Converter - Convert PDF to Images Online",
    seoDescription: "Convert PDF pages to high-quality JPG images. Free online tool with customizable quality settings and batch processing.",
    features: ["High-quality output", "Custom resolution", "Batch processing", "Multiple formats"],
    relatedTools: ["/jpg-to-pdf", "/split", "/compress", "/ocr"],
    category: "Convert & Create"
  },
  {
    href: "/rotate",
    title: "Rotate PDF",
    description: "Rotate PDF pages to the correct orientation (90, 180, 270 degrees).",
    icon: <RotateCw className="w-8 h-8 text-yellow-500" />,
    comingSoon: false,
    keywords: ["rotate pdf", "fix pdf orientation", "turn pdf pages", "pdf rotation", "flip pdf"],
    seoTitle: "Free PDF Rotator - Rotate PDF Pages Online",
    seoDescription: "Rotate PDF pages by 90, 180, or 270 degrees. Fix document orientation with our free online PDF rotation tool.",
    features: ["Multiple rotation angles", "Page-specific rotation", "Batch rotation", "Preview changes"],
    relatedTools: ["/organize", "/reorder", "/delete-pages", "/split"],
    category: "Organize & Edit"
  },
  {
    href: "/watermark",
    title: "Watermark PDF",
    description: "Add custom text or image watermarks to your PDF documents.",
    icon: <Stamp className="w-8 h-8 text-red-500" />,
    comingSoon: false,
    keywords: ["watermark pdf", "add watermark", "pdf branding", "document protection", "pdf stamp"],
    seoTitle: "Free PDF Watermark Tool - Add Watermarks to PDF Online",
    seoDescription: "Add text or image watermarks to PDF documents. Customize position, opacity, and rotation with our free online watermarking tool.",
    features: ["Text & image watermarks", "Custom positioning", "Opacity control", "Rotation options"],
    relatedTools: ["/protect", "/sign", "/page-numbers", "/compress"],
    category: "Security & Privacy"
  },
  {
    href: "/protect",
    title: "Protect PDF",
    description: "Encrypt your PDFs with a password for enhanced security.",
    icon: <Lock className="w-8 h-8 text-gray-500" />,
    comingSoon: false,
    keywords: ["protect pdf", "password pdf", "encrypt pdf", "secure pdf", "pdf security"],
    seoTitle: "Free PDF Password Protection - Secure PDF Files Online",
    seoDescription: "Protect PDF files with password encryption. Add security to sensitive documents with our free online PDF protection tool.",
    features: ["Password encryption", "User permissions", "Print restrictions", "Copy protection"],
    relatedTools: ["/unlock", "/watermark", "/sign", "/compress"],
    category: "Security & Privacy"
  },
  {
    href: "/unlock",
    title: "Unlock PDF",
    description: "Remove password protection from your PDF files.",
    icon: <Unlock className="w-8 h-8 text-orange-500" />,
    comingSoon: false,
    keywords: ["unlock pdf", "remove pdf password", "decrypt pdf", "pdf password remover", "open protected pdf"],
    seoTitle: "Free PDF Unlocker - Remove PDF Password Online",
    seoDescription: "Remove password protection from PDF files. Unlock encrypted PDFs with our free online PDF password removal tool.",
    features: ["Password removal", "Quick processing", "Secure unlocking", "No data retention"],
    relatedTools: ["/protect", "/merge", "/split", "/compress"],
    category: "Security & Privacy"
  },
  {
    href: "/delete-pages",
    title: "Delete PDF Pages",
    description: "Remove unwanted pages from your PDF document easily.",
    icon: <Eraser className="w-8 h-8 text-indigo-500" />,
    comingSoon: false,
    keywords: ["delete pdf pages", "remove pdf pages", "extract pdf pages", "pdf page removal", "trim pdf"],
    seoTitle: "Free PDF Page Deleter - Remove Pages from PDF Online",
    seoDescription: "Delete unwanted pages from PDF documents. Remove specific pages or page ranges with our free online PDF page deletion tool.",
    features: ["Select specific pages", "Page range deletion", "Preview before deletion", "Instant processing"],
    relatedTools: ["/split", "/organize", "/reorder", "/merge"],
    category: "Organize & Edit"
  },
  {
    href: "/reorder",
    title: "Reorder PDF Pages",
    description: "Rearrange the order of pages within your PDF document.",
    icon: <ListOrdered className="w-8 h-8 text-cyan-500" />,
    comingSoon: false,
    keywords: ["reorder pdf pages", "rearrange pdf", "organize pdf pages", "pdf page order", "sort pdf pages"],
    seoTitle: "Free PDF Page Reorder Tool - Rearrange PDF Pages Online",
    seoDescription: "Reorder and rearrange PDF pages with drag-and-drop interface. Organize your PDF documents with our free online tool.",
    features: ["Drag & drop interface", "Visual page preview", "Instant reordering", "Download organized PDF"],
    relatedTools: ["/organize", "/delete-pages", "/split", "/merge"],
    category: "Organize & Edit"
  },
  {
    href: "/organize",
    title: "Organize PDF",
    description: "Combine reordering and deletion to organize your PDF pages.",
    icon: <ListOrdered className="w-8 h-8 text-cyan-700" />,
    comingSoon: false,
    keywords: ["organize pdf", "pdf organizer", "manage pdf pages", "pdf page management", "restructure pdf"],
    seoTitle: "Free PDF Organizer - Manage PDF Pages Online",
    seoDescription: "Organize PDF pages by reordering, deleting, and managing content. Complete PDF organization tool with visual interface.",
    features: ["Page reordering", "Page deletion", "Visual management", "Complete organization"],
    relatedTools: ["/reorder", "/delete-pages", "/merge", "/split"],
    category: "Organize & Edit"
  },
  {
    href: "/page-numbers",
    title: "Add Page Numbers",
    description: "Insert customizable page numbers, headers, or footers into your PDF.",
    icon: <PlusCircle className="w-8 h-8 text-amber-500" />,
    comingSoon: false,
    keywords: ["add page numbers", "pdf page numbers", "number pdf pages", "pdf headers footers", "paginate pdf"],
    seoTitle: "Free PDF Page Number Tool - Add Page Numbers Online",
    seoDescription: "Add page numbers, headers, and footers to PDF documents. Customize format, position, and styling with our free online tool.",
    features: ["Custom numbering formats", "Header & footer options", "Position control", "Font customization"],
    relatedTools: ["/watermark", "/organize", "/merge", "/sign"],
    category: "Security & Privacy"
  },
  
  {
    href: "/ocr",
    title: "OCR (Text Recognition)",
    description: "Extract editable text from scanned PDFs and images.",
    icon: <Search className="w-8 h-8 text-green-400" />,
    comingSoon: false,
    keywords: ["ocr pdf", "extract text", "pdf text recognition", "scan to text", "pdf ocr online"],
    seoTitle: "Free PDF OCR Tool - Extract Text from Scanned PDFs",
    seoDescription: "Extract editable text from scanned PDFs and images using OCR technology. Free online optical character recognition tool.",
    features: ["Text extraction", "Multiple languages", "Image processing", "Editable output"],
    relatedTools: ["/form-filler", "/advanced-ocr", "/medical-analyzer"],
    category: "AI & Analysis"
  },
  {
    href: "/sign",
    title: "Sign / Annotate PDF",
    description: "Draw, type, or upload your signature and place it on your PDF.",
    icon: <Signature className="w-8 h-8 text-rose-500" />,
    comingSoon: false,
    keywords: ["sign pdf", "pdf signature", "annotate pdf", "digital signature", "pdf signing tool"],
    seoTitle: "Free PDF Signature Tool - Sign PDF Documents Online",
    seoDescription: "Sign PDF documents with digital signatures and annotations. Free online PDF signing tool with drawing and typing options.",
    features: ["Digital signatures", "Drawing tools", "Text annotations", "Signature placement"],
    relatedTools: ["/form-filler", "/protect", "/watermark", "/pdf-digital-signature"],
    category: "Forms & Documents"
  },
  {
    href: "/form-filler",
    title: "PDF Form Filler",
    description: "Add text, checkmarks, or other inputs to any PDF form.",
    icon: <Text className="w-8 h-8 text-lime-500" />,
    comingSoon: false,
    keywords: ["fill pdf form", "pdf form filler", "complete pdf forms", "pdf input", "form completion"],
    seoTitle: "Free PDF Form Filler - Complete PDF Forms Online",
    seoDescription: "Fill out PDF forms online with text, checkboxes, and signatures. Free PDF form completion tool with save functionality.",
    features: ["Form field detection", "Text input", "Checkbox support", "Form saving"],
    relatedTools: ["/sign", "/ocr", "/protect", "/pdf-form-creator"],
    category: "Forms & Documents"
  },


  {
    href: "/legal-analyzer",
    title: "Legal Document Analyzer",
    description: "AI-powered tool for legal document review and clause extraction.",
    icon: <FileText className="w-8 h-8 text-fuchsia-500" />,
    comingSoon: false,
    keywords: ["legal document analyzer", "contract review", "legal ai", "document analysis", "clause extraction"],
    seoTitle: "AI Legal Document Analyzer - Review Contracts Online",
    seoDescription: "Analyze legal documents with AI-powered contract review. Extract key clauses, identify risks, and get insights from legal texts.",
    features: ["AI-powered analysis", "Clause extraction", "Risk assessment", "Legal insights"],
    relatedTools: ["/medical-analyzer", "/ocr", "/form-filler"],
    category: "AI & Analysis"
  },
  {
    href: "/medical-analyzer",
    title: "Medical Document Analyzer",
    description: "AI-powered tool for medical document review and key information extraction.",
    icon: <FileHeart className="w-8 h-8 text-red-500" />,
    comingSoon: false,
    keywords: ["medical document analyzer", "medical ai", "health document review", "medical analysis", "patient document"],
    seoTitle: "AI Medical Document Analyzer - Review Medical Records",
    seoDescription: "Analyze medical documents with AI-powered review. Extract patient information, diagnoses, and medical insights from health records.",
    features: ["Medical AI analysis", "Patient data extraction", "Diagnosis identification", "Health insights"],
    relatedTools: ["/legal-analyzer", "/ocr", "/form-filler"],
    category: "AI & Analysis"
  },
  {
    id: 23,
    title: "PDF Metadata Editor",
    description: "Edit PDF metadata including title, author, subject, keywords, and creation date",
    icon: <Settings className="w-8 h-8 text-gray-500" />,
    href: "/tools/pdf-metadata-editor",
    category: "Edit",
    features: ["Edit title, author, subject", "Modify keywords and creation date", "Preserve document structure", "Client-side processing"],
    relatedTools: ["/protect", "/unlock", "/sign", "/watermark"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 24,
    title: "PDF Bookmark Manager",
    description: "Add, edit, and organize PDF bookmarks and navigation structure",
    icon: <Bookmark className="w-8 h-8 text-blue-500" />,
    href: "/tools/pdf-bookmark-manager",
    category: "Edit",
    features: ["Add custom bookmarks", "Edit existing bookmarks", "Organize bookmark hierarchy", "Export bookmark list"],
    relatedTools: ["/organize", "/reorder", "/page-numbers", "/split"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 25,
    title: "PDF Table Extractor",
    description: "Extract and export tables from PDF documents to CSV, Excel, or JSON format",
    icon: <Table className="w-8 h-8 text-green-500" />,
    href: "/tools/pdf-table-extractor",
    category: "Convert",
    features: ["Extract tables automatically", "Export to CSV/Excel/JSON", "Preview extracted data", "Handle complex table structures"],
    relatedTools: ["/ocr"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 26,
    title: "PDF Batch Processor",
    description: "Process multiple PDF files at once with various operations like merge, split, compress",
    icon: <Layers className="w-8 h-8 text-purple-500" />,
    href: "/tools/pdf-batch-processor",
    category: "Utility",
    features: ["Batch merge multiple PDFs", "Bulk compression", "Mass watermarking", "Batch operations"],
    relatedTools: ["/merge", "/compress", "/split", "/watermark"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 27,
    title: "PDF Form Creator",
    description: "Create interactive PDF forms with various field types including text, checkboxes, and signatures",
    icon: <FileBadge2 className="w-8 h-8 text-orange-500" />,
    href: "/tools/pdf-form-creator",
    category: "Create",
    features: ["Text input fields", "Checkboxes and radio buttons", "Dropdown menus", "Signature fields"],
    relatedTools: ["/form-filler", "/sign", "/pdf-digital-signature", "/invoice-generator"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 28,
    title: "Advanced OCR with AI",
    description: "Extract text from PDFs and images with AI-powered enhancement and formatting",
    icon: <Search className="w-8 h-8 text-teal-500" />,
    href: "/tools/advanced-ocr",
    category: "AI Tools",
    features: ["AI-enhanced text extraction", "Multiple language support", "Format preservation", "Confidence scoring"],
    relatedTools: ["/ocr", "/legal-analyzer", "/medical-analyzer"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 29,
    title: "PDF Accessibility Checker",
    description: "Check PDF documents for accessibility compliance and WCAG standards",
    icon: <CheckCircle className="w-8 h-8 text-green-600" />,
    href: "/tools/pdf-accessibility-checker",
    category: "Utility",
    features: ["WCAG compliance check", "Alt text validation", "Reading order analysis", "Color contrast testing"],
    relatedTools: ["/pdf-redaction", "/pdf-version-comparison", "/pdf-digital-signature", "/sign"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 30,
    title: "PDF Digital Signature",
    description: "Add legally binding digital signatures with certificate management and validation",
    icon: <Shield className="w-8 h-8 text-blue-600" />,
    href: "/tools/pdf-digital-signature",
    category: "Security",
    features: ["Digital certificates", "Signature validation", "Timestamp authority", "Legal compliance"],
    relatedTools: ["/sign", "/protect", "/unlock", "/form-filler"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 31,
    title: "PDF Redaction Tool",
    description: "Permanently remove sensitive information from PDF documents with verification",
    icon: <EyeOff className="w-8 h-8 text-red-600" />,
    href: "/tools/pdf-redaction",
    category: "Security",
    features: ["Content removal", "Metadata cleaning", "Visual verification", "Secure deletion"],
    relatedTools: ["/protect", "/unlock", "/pdf-accessibility-checker", "/sign"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 32,
    title: "PDF Version Comparison",
    description: "Compare different versions of PDF documents with visual diff highlighting",
    icon: <GitCompare className="w-8 h-8 text-indigo-600" />,
    href: "/tools/pdf-version-comparison",
    category: "Analysis",
    features: ["Visual diff", "Text comparison", "Layout changes", "Version tracking"],
    relatedTools: ["/pdf-accessibility-checker", "/ocr", "/legal-analyzer", "/medical-analyzer"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    id: 33,
    title: "PDF Annotation Collaboration",
    description: "Collaborate on PDF annotations with team members and export shared comments",
    icon: <MessageSquare className="w-8 h-8 text-cyan-600" />,
    href: "/tools/pdf-annotation-collaboration",
    category: "Collaboration",
    features: ["Team annotations", "Comment threads", "Export annotations", "Review workflows"],
    relatedTools: ["/sign", "/form-filler", "/pdf-digital-signature", "/pdf-batch-processor"],
    category: "Advanced PDF Tools",
    isNew: true
  },
  {
    href: "/invoice-generator",
    title: "PDF Invoice Generator",
    description: "Create professional invoices with GST support, multiple currencies, and customizable templates.",
    icon: <Calculator className="w-8 h-8 text-green-500" />,
    comingSoon: false,
    keywords: ["pdf invoice generator", "create invoice", "invoice maker", "business invoice", "gst invoice", "professional invoice"],
    seoTitle: "PDF Invoice Generator - Create Professional Invoices Online",
    seoDescription: "Generate professional PDF invoices with GST support, multiple currencies, and customizable templates. Perfect for businesses and freelancers.",
    features: ["Professional invoice templates", "GST and tax calculations", "Multiple currency support", "Client and company management"],
    relatedTools: ["/form-filler", "/sign", "/watermark"],
    category: "Business Tools",
    isNew: true
  },
  {
    href: "/qr-generator",
    title: "QR Code Generator",
    description: "Generate QR codes for URLs, text, WiFi, contact cards, and more. Export as PNG or PDF.",
    icon: <QrCode className="w-8 h-8 text-purple-500" />,
    comingSoon: false,
    keywords: ["qr code generator", "qr code maker", "wifi qr code", "vcard qr code", "url qr code", "qr code pdf"],
    seoTitle: "QR Code Generator - Create QR Codes for PDF Online",
    seoDescription: "Generate QR codes for URLs, WiFi, contact cards, and more. Export as PNG or PDF with customizable size and quality.",
    features: ["Multiple QR code types", "Customizable size and quality", "WiFi and vCard support", "PNG and PDF export"],
    relatedTools: ["/watermark", "/merge", "/form-filler"],
    category: "Convert & Create",
    isNew: true
  },
  {
    href: "/certificate-generator",
    title: "Certificate Generator",
    description: "Create professional certificates for courses, training, achievements, and more with customizable templates.",
    icon: <Award className="w-8 h-8 text-yellow-500" />,
    comingSoon: false,
    keywords: ["certificate generator", "certificate maker", "course certificate", "training certificate", "achievement certificate"],
    seoTitle: "Certificate Generator - Create Professional Certificates PDF",
    seoDescription: "Generate professional certificates for courses, training, achievements with customizable templates and styling options.",
    features: ["Multiple certificate templates", "Customizable colors and styles", "Professional layouts", "Automatic certificate IDs"],
    relatedTools: ["/sign", "/watermark", "/form-filler"],
    category: "Business Tools",
    isNew: true
  },
  {
    href: "/portfolio-creator",
    title: "Portfolio Creator",
    description: "Create professional PDF portfolios with customizable sections for experience, education, skills, and projects.",
    icon: <Briefcase className="w-8 h-8 text-blue-500" />,
    comingSoon: false,
    keywords: ["portfolio creator", "pdf portfolio", "professional portfolio", "resume builder", "cv maker"],
    seoTitle: "Portfolio Creator - Create Professional PDF Portfolios",
    seoDescription: "Create professional PDF portfolios with customizable sections for experience, education, skills, and projects.",
    features: ["Professional portfolio templates", "Multiple customizable sections", "Experience and education tracking", "Skills and projects showcase"],
    relatedTools: ["/certificate-generator", "/invoice-generator", "/form-filler"],
    category: "Business Tools",
    isNew: true
  },
  {
    href: "/report-generator",
    title: "Report Generator",
    description: "Create professional business reports with sections, metrics, charts, and recommendations.",
    icon: <FileText className="w-8 h-8 text-indigo-500" />,
    comingSoon: false,
    keywords: ["report generator", "business report", "pdf report", "professional report", "report maker"],
    seoTitle: "Report Generator - Create Professional Business Reports PDF",
    seoDescription: "Create professional business reports with sections, metrics, charts, and recommendations. Perfect for business analysis and reporting.",
    features: ["Multiple report templates", "Key metrics dashboard", "Customizable sections", "Professional formatting"],
    relatedTools: ["/portfolio-creator", "/invoice-generator", "/certificate-generator"],
    category: "Business Tools",
    isNew: true
  }
];